////
|metadata|
{
    "name": "piechart-selection",
    "controlName": ["{PieChartName}"],
    "tags": ["Charting","Data Presentation","How Do I"],
    "guid": "",
    "buildFlags": ["SL","WPF","win-phone","WINFORMS","ANDROID","XAMARIN"],
    "createdOn": "2014-06-05T19:53:12.0788999Z"
}
|metadata|
////

= 選択

このトピックでは、link:{DataPieChartLink}.{DataPieChartName}.html[{DataPieChartName}] コントロールの選択機能を有効にして使用する方法について説明します。

このトピックは、以下のセクションで構成されています。

* <<Requirements,要件>>
* <<Overview,概要>>
* <<SelectionBehaviors, 選択動作>>
* <<SelectionModes,選択モード>>
* <<SelectionEvents,選択イベント>>
* <<RelatedTopics,関連コンテンツ>>

[[Requirements]]
=== 要件

このトピックは、ユーザーがlink:data-pie-chart-data-binding.html[データ バインディング] トピックを既に読んでいることを前提とし、はじめにそのコードを使用します。

[[Overview]]
== 選択の概要

{DataPieChartName} は、チャートにプロットされたスライスをマウスでクリックしてスライスを選択できる機能をサポートしています。チャートの選択機能のさまざまな側面について、以下に説明します。

[[SelectionBehaviors]]
=== 選択動作

`SelectionBehavior` の主な 2 つのオプションは `PerDataItemSingleSelect` と `PerDataItemMultiSelect` で、それぞれ単一選択と複数選択を有効にします。

[[SelectionModes]]
=== 選択モード

`SelectionMode` プロパティは、円チャートのスライスが選択された場合にどのように反応するかを決定します。このプロパティは、`SeriesSelectionMode` 列挙体によって定義されます。以下はその列挙体のオプションとその機能です。

- `Brighten`: 選択したスライスが強調表示されます。
- `FadeOthers`: 選択したスライスは同じ色のまま残り、他のスライスは色が薄くなります。
- `FocusColorFill`: 選択したスライスの背景が {DataPieChartName} コントロールの `FocusBrush` に変更されます。
- `FocusColorOutline`: 選択されたスライスには、{DataPieChartName} コントロールの `FocusBrush` によって定義された色のアウトラインが表示されます。
- `FocusColorThickOutline`: 選択されたスライスには、{DataPieChartName} コントロールの `FocusBrush` によって定義された色のアウトラインが表示されます。このアウトラインの太さは、コントロールの `Thickness` プロパティを使用して設定することもできます。
- `GrayscaleOthers`: 選択されていないスライスにはグレー色のフィルターが適用されます。
- `None`: 選択されたスライスには影響はありません。
- `SelectionColorFill`: 選択されたスライスの背景が {DataPieChartName} コントロールの `SelectionBrush` に変更されます。
- `SelectionColorOutline`: 選択されたスライスには、{DataPieChartName} コントロールの `SelectionBrush` によって定義された色のアウトラインが表示されます。
- `SelectionColorThickOutline`: 選択されたスライスには、{DataPieChartName} コントロールの `FocusBrush` によって定義された色のアウトラインが表示されます。このアウトラインの太さは、コントロールの `Thickness` プロパティを使用して設定することもできます。
- `ThickOutline`: 選択されたスライスには、{DataPieChartName} コントロールの `Thickness` プロパティに応じて太さが異なるアウトラインが適用されます。

[[SelectionEvents]]
=== 選択イベント

スライスが選択されると、その基になるデータ項目がチャートの `SelectedSeriesItems` コレクションに追加されます。そのため、{DataPieChartName} は `SelectedSeriesItemsChanged` イベントを公開して、スライスが選択されてこのコレクションが変更されたことを検出します。

[[CodeExample]]

== コード例

ifdef::wpf[]

*XAML の場合:*

[source,xaml]
----
TODO
----

*C# の場合:*

[source, csharp]
----
{DataPieChartName} dataPieChart = new {DataPieChartName}()
{                
    DataSource = data,
    SelectionBehavior = SeriesSelectionBehavior.PerDataItemMultiSelect,
    SelectionMode = SeriesSelectionMode.SelectionColorFill,
    SelectionBrush = Brushes.DodgerBlue
};
----

endif::wpf[]

ifdef::win-forms[]

*C# の場合:*

[source,csharp]
----
{DataPieChartName} dataPieChart = new {DataPieChartName}()
{                
    DataSource = data,
    Dock = DockStyle.Fill,
    SelectionBehavior = SeriesSelectionBehavior.PerDataItemMultiSelect,
    SelectionMode = SeriesSelectionMode.SelectionColorFill,
    SelectionBrush = Brushes.DodgerBlue
};
----

endif::win-forms[]

[[RelatedTopics]]
== 関連コンテンツ

* link:data-pie-chart-data-binding.html[データ バインディング]
* link:data-pie-chart-others-category.html[その他カテゴリ]