////

|metadata|
{
    "name": "introduction-tips-for-installing-infragistics-windows-forms",
    "controlName": [],
    "tags": ["Getting Started","Tips and Tricks"],
    "guid": "{AD766458-E5D5-48CB-88EB-DC1C426C18F1}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= {ProductName} のインストールのヒント

ソフトウェアのインストールは予定どおりにいかない場合があります。ユーザーごとにマシンの設定が異なることが分かっており、Infragistics を可能な限りスムーズにインストールすることを支援するトラブルシューティングのリストを以下に提供します。

* Infragistics をインストールするには、管理者としてログインする必要があります。このログインはシステム レジストリをアップデート可能であることが必要です。
* テンポラリ ファイルを含み、インストールに十分なスペースがあることを確認します。デフォルトで、Windows は「C:\WINDOWS\Temp」ディレクトリにテンポラリ ファイルを保存します。
* Visual Studio がインストールされている必要がありますが、インストールの間とツールボックス ユーティリティを実行する時には閉じておく必要があります。
* インストーラ ファイルは、ネットワーク ドライブから適切に実行しない場合があります。代わりにローカルのハードディスクにコピーします。
* トライアル版の Infragistics をすでにインストールしてある場合は、ソフトウェアをアンインストール/再インストールする必要はありません。適切なディレクトリ（たとえば {InstallPath} からインストーラ ファイル（たとえば Infragistics{ProductVersion}_CLR2x.exe）を実行して、インストール ウィザードで製品キーを入力できます。
* インストールの間にライセンス キーが無効というエラーが発生した場合、キーを正しく記入したことを最初に確認します。入力したキーが正しい場合、インストールをキャンセルし（試しにインストールしないでください）、コンピュータを再起動して、再度インストールします。
* ファイル名（すべてのパス情報を含む）は 256 文字を超えることはできません。これは Windows の制限です。「8.3」表記を使用することで、弊社のインストーラはこれを内部で処理します。たとえば、「C:\Program Files\」は「C:\PROGRA~1\」として参照されます。Infragistics をインストールするときに長すぎる宛先フォルダ名を提供すると、「ファイルが見つからないか壊れています」というエラー メッセージが表示される場合があります。
* Infragistics の複数のコンポーネントを組み合わせてインストールしてから後でそのひとつを削除した場合、既知の問題を発生する可能性があります。これらの問題を解決するには、必要な Infragistics を再インストールしてください。
* AppStylist® for Windows Forms では、インストールした Infragistics Style Library（.isl）ファイルのいずれかを修正して、変更を isl 存したい場合には、変更を必ず別ファイルで保存します。これによって、カスタマイズした .isl が Infragistics ホット フィックスによって上書きされたり、 Infragistics のアンインストール中に削除されないことが保証されます。