////

|metadata|
{
    "name": "styling-guide-role-editor",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{B01BBDA8-EF2A-4B60-8085-985D3D3B7303}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= ロール エディタ

スタイルしたい特定の UI ロールを見つけたら、UI ロール エディタの出番です。キャンバス領域でキーボード ショートカットを使用する、またはスタイル エクスプローラのツリーでいずれかをクリックすることによって、UI ロールを選択すると、AppStylist for Windows Forms ユーザー インターフェイスの一番下に UI ロール エディタが表示されます。タブを使用して UI ロールのさまざまな状態をナビゲートします。状態とは、UI ロールがなることができる特定のモードです。UI ロールはランタイムに一度に複数の状態になることも可能です。たとえば、セルは同時に Selected、HotTracked、および Active になることができます。UI ロールがなることができる状態のグループは 3 つあります。

* 一般 – 一般の状態はほとんどの UI ロールに属しています。UI ロールは一度にひとつまたは複数のこれらの状態になることができます。これらの状態のいくつかは、すべての UI ロールに適用されるわけではありません。したがって常にすべてを見ることできません。
* その他 – その他の状態は現在のUI ロールに限って適用できる状態です。
* グリッド – グリッド状態は WinGrid およびグリッドを使用するその他のコンポーネントに限って適用されます。

これらの 3 つのタブの下に含まれる各状態は、選択されたタブのペインを使用してスタイルできます。これらのペインを使用すると、任意の UI ロールの [Background]、[Border]、[Font]、[Image] および [Other] の各プロパティをスタイルできます。リソースを UI ロールに適用することも可能です。リソースに関する詳細は、 link:styling-guide-using-resources-with-stylesets.html[「スタイルセットとリソースを使用」]を参照してください。

[NOTE]
====
*注:* スタイル エクスプローラで [リソース] タブによってリソースを修正しようとする場合、UI ロール エディタはリソース エディタで置き換えられます。唯一の違いは、リソース エディタはエディタの一番上にタブ付きのインタフェースがないこと（状態ではなくリソースを編集するため）と、[リソース] ペインが非表示であることです。
====

以下のセクションでは、UI ロール エディタの各プロパティと、プロパティが相互にどのように影響し合うのかに関する詳細な説明が提供されます。

* link:styling-guide-background-pane.html[背景]
* link:styling-guide-border-pane.html[境界線]
* link:styling-guide-font-pane.html[フォント]
* link:styling-guide-image-pane.html[画像]
* link:styling-guide-other-pane.html[その他]
* link:styling-guide-resources-pane.html[リソース]