////

|metadata|
{
    "name": "styling-guide-application-styling-the-developers-perspective",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{8EEED3DE-C0B1-450D-A716-04DED8E3C54F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= アプリケーション スタイリング：開発者の観点

アプリケーション スタイリングは、アプリケーション開発者には開発に必要な時間を提供し、グラフィック デザイナにはデザインに必要なツールを提供します。アプリケーション開発者の観点からアプリケーション スタイリングを見てみましょう。最初にアプリケーション スタイリングがいかに開発者のメリットとなるのかを確認し、次にアプリケーション スタイリングが使用されているかいないかにかかわらず、どの程度の影響を及ぼすかを確認します。

== 線の定義

開発者にとってのアプリケーション スタイリングの主要なメリットのひとつは時間です。アプリケーション スタイリングは、アプリケーションの開発とアプリケーションのスタイリングの間の線をはっきりと規定するようになったため、開発者は自分が最も知っていること、すなわち開発により多くの時間を使うことができます。とは言っても、アプリケーション スタイリングは開発者から始まるわけではありません。技術的に言うと、グラフィック デザイナから始まるわけでもありません。開発者とグラフィック デザイナの両者は、別々ですが、同時にそれぞれの仕事を実行します。それがアプリケーション スタイリングの長所です。当分の間、グラフィック デザイナのことは脇に置いておいて、アプリケーション スタイリングの助けを借りない場合に、アプリケーション開発者が日常的なルーチン業務をどのように実行するのかを見てみましょう。

== 味気なく完成度が低い

アプリケーション開発者の Mike は、彼の会社の次回のソフトウェア リリースに向けてバグのないユーザー インタフェースを開発するために毎日一生懸命働いています。数週間に及ぶコーディングとデバッグの激務の後、彼は UI の最終的な仕上げに入りました。ところが、UI は適切に機能するのですが、見栄えは味気なく完成度の低いものでした。Mike の上司は、2 日間の作業でアプリケーションの見栄えを良くするようにと指示しました。どんなにがんばっても、アプリケーションを最終的に仕上げるために Mike は適切に色とスタイルを組み合わせることができません。

Mike を本当に気の毒だと思うとともに、我々の何人かは彼と全く同じ経験をしています。ところが、アプリケーション スタイリングは Mike と彼の会社により優れた方法を提供します。AppStylist for Windows Forms の支援を受けて、Application Styling Framework™（ASF）を Mike の会社が採用したらどうなるのかを見てみましょう。

== ちょうどいい時に支援が到着

Mike はへとへとに疲れ、この 2、3 週間のストレスで本当にまいっていました。以前の製品リリースであったらもっと良かったであろうことは分かっており、必要なスキル セットを持っていなかったに過ぎません。ところが、Mike の上司は開発に対する新しいアプローチを採用することを決めました。Infragistics 独自の ASF を採用して、Mike の上司は、UI のスタイリングという業務は AppStylist を使用するグラフィック デザイナに任せました。Mike はアプリケーション スタイリングについてあまり知識がありませんでしたし、知る必要もありませんでした。Mike は彼が最も得意とするソフトウェアの開発を開始します。開発が終わると、Mike は前回のソフトウェアのリリースを思い出して、スタイリングを始めなくてはいけないと思い、うんざりとします。ところが突然、Mike はグラフィック デザイナの Kate から Infragistics Style Library（.isl）ファイルを受け取ります。

____
「これを私にどうしろと言うんだ?」とMike は尋ねます。
____

____
Kate は「コード 1 行を Main メソッドに追加するだけで準備完了です」と答えます。
____

____
「それだけかい?」と Mike は驚いて言います。「コード 1 行だけでアプリケーション全体がスタイリングできるの?」
____

____
Kate は笑って言います。「1 行だけよ」
____

Mike がアプリケーションを開発している間に Kate がアプリケーションのスタイリングを行っていたことを Mike は知りません。この新しい協力関係によって、Mike は UI を微調整するためのソフトウェア開発サイクルの最終段階から完全に解放されました。また最初の時には気づかなかったバグをいくつか見つけました。Mike が本当に感激したのは、UI の見栄えが大変新鮮かつ新しいのに Kate は彼のコードには一切触れなかったことです。Kate はこの作業すべてをどのようにしてできたのでしょうか? link:styling-guide-application-styling-the-graphic-designers-perspective.html[グラフィック デザイナの観点]からアプリケーション スタイリングを見てみましょう。