////

|metadata|
{
    "name": "styling-guide-application-styling-framework-asf",
    "controlName": [],
    "tags": [],
    "guid": "{E29067E9-77F9-4A8C-9B2F-9DACFF781AA9}",  
    "buildFlags": [],
    "createdOn": "2006-11-04T00:00:00Z"
}
|metadata|
////

= Application Styling Framework (ASF)

できる限りシンプルにアプリケーションのスタイリングができるように弊社は Application Styling Framework™ (ASF) を設計しました。ASF を使用することによって、ひとつのスタイルを作成して（スタイルセットとして知られている）、それを他のアプリケーションに適用することができます。Infragistics AppStylist™ でスタイルセットを作成し、Infragistics.Win.AppStyling 名前空間にあるカスタム API を使用してそのスタイルセットをアプリケーションに適用します。これで終わりではありません。InboxControlStyler コンポーネントでインボックス コントロールをスタイルしたり、自分独自のアプリケーションで AppStylist のランタイム バージョンを実行することも可能です。

* link:styling-guide-asf-overview.html[ASF 概要] -- ASF 概要は ASF の基本と異なるコンポーネントがどのように互いに作用するかについて説明します。
* link:styling-guide-setting-up-your-application-for-styling.html[スタイリングのためにアプリケーションを設定] -- アプリケーション開発者が知っておく必要がある事柄で、たとえば、スタイル ライブラリのロード方法やランタイムにスタイルセットを変更する方法です。情報はここで見つけることができます。
* link:styling-guide-styling-your-application.html[アプリケーションのスタイリング] -- StyleSet を作成するには、AppStylist を使用します。スタイル ライブラリ、スタイル セット、リソースなどの作成を説明します。