////

|metadata|
{
    "name": "styling-guide-asf-overview",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{6B00CC8C-DDAD-4BB5-ADA8-30626D88D0A4}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= ASF 概要

Application Styling Framework (ASF) は、アプリケーションのスタイリング時に十分な柔軟性を提供するように設計されています。アプリケーション開発者はグラフィック デザイナの支援を得て、そのプロセスで時間やリソースを節約できます。開発者とグラフィック デザイナ間のコラボレーションは、ASF の中心です。ASF の十分に管理されたコードベースによって、アプリケーション全体がアプリケーション スタイリングによってどのような影響を受けるかを操作するために必要となるすべてのツールを開発者に提供します。スタンドアロン アプリケーションである Infragistics AppStylist™ は、グラフィック デザイナがひとつのアプリケーションをスタイルするためだけでなく、開発者が適用するために必要なすべてのアプリケーションをスタイルするために使用できる素晴らしいツールです。

ASF は Infragistics の Presentation Layer Framework (PLF) に連動して機能します。ASF は、ほとんどの視覚的コントロールの複数の局面をスタイルするためにユニークな方法で PLF の Appearance Object を使用します。この機能は、AppStylist のプロパティ パネルの UI ロール エディタの作業で見ることができます。

== ASF コンポーネント

* link:appstylistruntime.html[AppStylistRuntime] ASF は、単一のメソッドを使用して開発者が起動できる AppStylist のランタイム バージョンと共に出荷されます。この技術を使用すれば、開発者はスタイルをオンザフライで変更できます。もうひとつの使用は、自身のアプリケーションに AppStylist をパッケージすることで、そうすればグラフィック デザイナは、AppStylist のスタンドアロン バージョンと共に出荷されるデフォルトのキャンバスではなく、スタイルの変更がアプリケーションにどのように影響を与えるかを確認できます。
* link:win-inboxcontrolstyler.html[InboxControlStyler] – InboxControlStyler は、インボックス コンポーネントをスタイルするために AppStylist を使用したい場合には必要です。AppStylist がインボックス コンポーネントをスタイルすることができるようにするために開発者に求められるのは、コンポーネント トレイにこのコンポーネントを単に配置することだけです。ただし、インボックス コンポーネントには Appearance Object や PLF の一部を使用しないことに注意してください。したがって、ForeColor、BackColor、および Font 変更など、開発者が使用できるシンプルなインボックス スタイリング オプションだけを持ちます。ASF はインボックス コンポーネントに補足的なスタイリング オプションを追加できません。
* AppStylistSupport – AppStylistSupport アセンブリには、AppStylist 自体を構成する複数のコンポーネントが含まれます。これらのコンポーネントは、開発者が使用できるようにされていますが、現在はヘルプではサポートされていません。このアセンブリは、AppStylistRuntime コンポーネントも備えており、これはサポートされています。

== 利点

* *時間の節約* – ASF の側面を使用すると会社での時間を節約できます。Appearance Object を使用することで同じスタイルを繰り返し適用するのではなく、ASF はひとつのスタイル ライブラリを使用して、開発者が選択したすべてのアプリケーションに同じスタイルを適用することができます。重複する作業が不要になります。
* *より効率的に作業* – AppStylist は、開発者がアプリケーション自体で作業を続行する間、グラフィック デザイナが使用するように設計されています。このように作業負荷を分割することで、開発者の作業が軽減されます。また、開発者とグラフィック デザイナは、それぞれの作業を待つことなく同時に作業することができます。これによってより効率的な作業フローが可能になり、時間をより効率的に使用できます。
* *ワールド クラスのサポート* – AppStylist には、徹底的に設計されたヘルプ システムが付属しています。グラフィック デザイナを対象として、ヘルプ コンテンツには、F1 のコンテキスト依存ヘルプ機能もあります。開発者のためのヘルプも用意されています。メインの {ProductName} の開発ガイドのヘルプには、特に開発者を対象とした支援と完全な AppStylist ヘルプが含まれています。