////

|metadata|
{
    "name": "styling-guide-application-styling-the-graphic-designers-perspective",
    "controlName": [],
    "tags": ["Styling","Theming"],
    "guid": "{2936ED0C-C22B-4779-996E-3B6E0F3AC878}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= アプリケーション スタイリング：Application Styling:グラフィック デザイナの観点

アプリケーション スタイリングは、アプリケーション開発者には開発に必要な時間を提供し、グラフィック デザイナにはデザインに必要なツールを提供します。グラフィック デザイナの観点からアプリケーション スタイリングを見てみましょう。最初にアプリケーション スタイリングがいかにグラフィック デザイナのメリットとなるのかを確認し、次にアプリケーション スタイリングが使用されているかいないかにかかわらず、どの程度の影響を及ぼすかを確認します。

== 必要なツールを提供

グラフィック デザイナにとってのアプリケーション スタイリングの主要なメリットのひとつは親しみやすさです。グラフィック デザイナは、不慣れな Visual Studio Integrated Developer's Environment（IDE）を大変な思いをして使用する必要はもはやありません。アプリケーション スタイリングはグラフィック デザイナに配慮して設計された固有なツール Infragistics AppStylist for Windows Forms をグラフィック デザイナに提供します。Infragistics AppStylist は、コード 1 行のみで任意の Visual Studio プロジェクトにロード可能な強力なスタイル ライブラリを作成するための能力をグラフィック デザイナに提供します。とりあえず、アプリケーション開発者のことは脇に置いておいて、アプリケーション スタイリングの助けを借りない場合に、グラフィック デザイナがどのように実行するのかを見てみましょう。

== 不慣れな領域

Kate は彼女の会社でグラフィック デザイナとして働いています。彼女は非常に才能があり、グラフィック ユーザー インタフェース設計を支援する多くの機会で会社の期待に応えてきました。ところが、アプリケーション開発者と効果的に協力できないことでどうしたものかと思っていました。最初に、Kate の会社はソース コントロールを使用します。開発者がグラフィック デザイナよりも優先順位が高いと考えて、Kate は彼女が必要とするコードへのアクセス権を持っていません。彼女の上司は結果を期待していますが、彼女は必要な時に結果を出すことができません。第 2 に、Visual Studio プロジェクトにアクセスする時に、彼女が探し求めている視覚的効果を与えるプロパティを見つけ出すために、常にプロパティ ウィンドウを隅から隅まで探します。Kate は、Adobe® および Macromedia® 製品などのグラフィック中心のソフトウェアでの作業に慣れています。Visual Studio IDE は Kate にとって不慣れな領域です。結局、これらのプロパティのいくつかを変更する時、Kate は知らないうちにアプリケーションにバグを入れてしまいました。このため開発者は以前よりもコードに対する保護を強化するようになりました。

誰もが最もしたくないことは、快適な領域を離れることです。締め切りに間に合わない、不慣れなユーザー インタフェースを使用する、開発者との緊張した関係、Kate は手一杯でした。ところが、アプリケーション スタイリングはこれらすべての場合を考慮に入れて、Kate とアプリケーション開発者の両者がメリットを得る代替案を提供します。Infragistics AppStylist の支援を受けて、Application Styling Framework™（ASF）を Kate の会社が採用したらどうなるのかを見てみましょう。

== ストレス レベルが下がる

前回のソフトウェア リリース以降、Kate は開発者と良い関係ではありませんでした。彼女の上司は、彼女とアプリケーション開発者が協力するためのより良い方法があるに違いないと考えました。それからまもなく、Kate は Infragistics AppStylist という新しいソフトウェア パッケージを受け取ります。素早くインストールして、ソフトウェアを起動します。手順ごとに開始する方法を説明した [開始] ページが表示されました。Visual Studio のプロパティ ウィンドウでうんざりするほど検索していた作業を説明する、動的に案内する独自のツール チップの支援によって、直感的なユーザー インタフェースを自在に操作できるようになるまでさして時間はかかりませんでした。まもなく、彼女は WinGrid 全体のスタイリングを終え、コードには一切ふれなかったことに気づきます。特定のコンポーネント用に設計された複数の異なるキャンバスに彼女が行ったすべての変更が直接彼女の前に表示されます。最後に、彼女は Infragistics Style Library（.isl）ファイルとして自分の作業を残し、アプリケーション開発者の一人にそれを手渡します。

Infragistics AppStylist が Kate の問題をひとつずつ解決したことは極めて明らかです。Visual Studio IDE の危険な環境を回避すると同時に彼女固有のペースで作業をすることができるようになりました。Infragistics AppStylist はグラフィック デザイナに配慮して設計されているため、Kate はその他のグラフィック デザイン ソフトウェアに似たユーザー インタフェースを簡単にナビゲートすることができました。アプリケーション スタイリングからメリットを得た社員は Kate だけではありません。アプリケーション開発者はアプリケーション スタイリングから非常に多くのメリットを得ています。 link:styling-guide-application-styling-the-developers-perspective.html[開発者の観点]からアプリケーション スタイリングを見てみましょう。