////
|metadata|
{
    "name": "win-whats-new-new-infragistics-word-library",
    "controlName": ["Infragistics Word Library"],
    "tags": ["Exporting"],
    "guid": "d4bdb76f-cea9-4041-9032-1b60a907954e",
    "buildFlags": [],
    "createdOn": "2011-05-13T15:01:37.4186752Z"
}
|metadata|
////

= 新しい Infragistics Word ライブラリ

今回の {ProductName} 2011 Volume 1 のリリースでは、新しい Infragistics® Word® ライブラリが採用されました。Word ライブラリによって、Microsoft® Word ドキュメントを作成できます。この作成機能は、オブジェクト モデル アプローチとフォーワードのみのストリーマー アプローチの両方で実装できます。これらの長所と短所は、 link:word-about-infragistics-word-library.html[「Infragistics Word ライブラリについて」]で説明します。

今回のリリースで使用可能な Word 機能は以下の通りです。

* 太字、斜体、下線、カラーなどの文字書式
* 段落
* フォント
* 画像
* ハイパーリンク
* 図形
* 表
* ページ レイアウト、余白、ヘッダー、フッター、改ページ、ページ番号

この新しい Word ライブラリを使用して、WinGrid™ と WinFormattedTextEditor™ から Word にデータをエクスポートすることもできます。詳細は、以下の関連トピックを照してください。

== 関連トピック

* link:word-understanding-infragistics-word-library.html[Infragistics Word ライブラリの理解]
* link:word-using-the-infragistics-word-library.html[Infragistics Word ライブラリの使用]
* link:whats-new-new-wingridwordwriter.html[新しい WinGridWordWriter]
* link:whats-new-new-winformattedtextwordwriter.html[新しい WinFormattedTextWordWriter]