////

|metadata|
{
    "name": "win-snaplines-whats-new-2005-3",
    "controlName": [],
    "tags": [],
    "guid": "{AE1ECB39-FB96-440C-B1F1-1F4E516963D1}",  
    "buildFlags": ["win-forms"],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= SnapLines

Visual Studio 2005（.NET Framework 2.0）には、デザイン時のコントロールのレイアウトを容易にするためにスナップラインの概念が導入されました。スナップラインとは、ユーザーインターフェイスに動的に作成される水平および垂直の線分です。スナップラインは開発者がコンテナー内部のコントロールのレイアウトをデザインするときに役立ちます。スナップラインは、１つ以上のコントロールを選択して移動しているときに、それが別のコントロールまたはコントロールのセットに揃う位置に近づくと表示されます。スナップラインを越えてさらに動かそうとすると、その位置にコントロールが"スナップ"します。

スナップラインは、コントロールの端が別のコントロールまたはコンテナーの境界に近づくと、動的に自動生成されます。これは、コントロールをツールボックスから追加したときや、マウス操作またはキーボードコマンドによってコントロールを移動またはサイズ変更したときに起こります。コントロールには通常、水平と垂直の両方のスナップラインが定義されています。 四角形のコントロールでは、これらは普通４つの辺すべてからの延長線になります。

開発者がスナップラインを操作するには、コントロールの Margin プロパティと Padding プロパティを設定します。コンテナーの境界線からのスナップラインの距離は、コントロールの Margin プロパティとコンテナーの Padding プロパティの値の合計です。

Infragisticsコントロールには必ずコントロールの上下左右に沿ったスナップラインがあります。一部のコントロールにはこれに加えて、テキスト要素の下端に沿ったテキストベースラインスナップラインもあります。スナップラインの詳細については、MicrosoftのWebサイトを参照してください。ienumerable についての Microsoft 記事