////

|metadata|
{
    "name": "wincontrolcontainereditor",
    "controlName": ["WinControlContainerEditor"],
    "tags": ["Getting Started"],
    "guid": "{1E9913B6-D801-4F66-BA28-269F4544D278}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinControlContainerEditor

WinControlContainerEditor コントロールに関連した概要/タスクベースの情報のすべてが収められている領域を探しているのであれば、このページをご覧ください。このセクションは、コントロールについての概要からアプリケーションで使用する理由、コントロールを使用して共通タスクを達成するための方法の手順などの WinControlContainerEditor についての有益な情報を含んでいます。

以下のリンクをクリックして、WinControlContainerEditor™ コントロールについての情報にアクセスします。

== link:wincontrolcontainereditor-understanding-wincontrolcontainereditor.html[WinControlContainerEditor の理解]

このセクションには WinControlContainerEditor コントロールの機能をより理解するための情報があります。なぜアプリケーションのビルドの一部として使用するかも説明します。

== link:wincontrolcontainereditor-using-wincontrolcontainereditor.html[WinControlContainerEditor の使用]

このセクションには役に立つ短いトピックがあり、WinControlContainerEditor コントロールを使って特定の作業を実行する方法を示すサンプルコードが付いています。

== link:wincontrolcontainereditor-api-overview.html[API の概要]

このトピックは、WinControlContainerEditor コントロールでプログラミング中に作業する名前空間とクラスをリストします。このトピックでリストされた名前空間とクラスは、「{ProductName} ヘルプ」の「API参照ガイド」セクションへリンクしていて便利です。