////

|metadata|
{
    "name": "winchart-new-properties-to-determine-the-scrolled-or-scaled-axis-whats-new-2006-3",
    "controlName": [],
    "tags": [],
    "guid": "{7B86B195-29FC-4489-893F-689A52E7C3D1}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= スクロールまたはスケールされた軸を判断するための新しいプロパティ

2006 Volume 3 リリースでは、WinChart スケーリングおよびスクローリング イベントの機能が拡張されました。エンド ユーザーがチャートを拡大/縮小またはチャートをスクロールアップ/ダウンする時、どの軸（X または Y）がスクロールされるかを判断できます。

以下の 2 つのプロパティが pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartscrollscaleeventargs.html[ChartScrollScaleEventArgs]"]  クラスに追加されました。

* pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartscrollscaleeventargs~axis.html[Axis]"] 
* pick:[win-forms="link:{ApiPlatform}win.ultrawinchart{ApiVersion}~infragistics.ultrachart.shared.events.chartscrollscaleeventargs~axisnumber.html[AxisNumber]"] 

== 関連トピック

link:chart-determine-which-axis-is-being-scrolled-or-scaled.html[スクロールまたはスケールする軸を決定する]

link:chart-scrolling-and-scaling-charts.html[チャートのスクロールとスケール]