////

|metadata|
{
    "name": "windesktopalert",
    "controlName": ["WinDesktopAlert"],
    "tags": [],
    "guid": "{86CD14B3-822F-4C19-A26F-F8E3177BB595}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinDesktopAlert

WinDesktopAlert コンポーネントに関連した概要/タスクベースの情報のすべてが収められている領域を探しているのであれば、このページをご覧ください。このセクションは、コンポーネントについての概要からアプリケーションで使用する理由、コンポーネントを使用して一般的なタスクを完了するための方法の手順などの WinDesktopAlert についての有益な情報を含んでいます。

以下のリンクをクリックすると、WinDesktopAlert コントロールに関する重要な情報にアクセスします。

== link:windesktopalert-understanding-windesktopalert.html[WinDesktopAlert の理解]

このセクションでは、WinDesktopAlert コンポーネントの機能をより良く理解するために助けとなるあらゆる情報や、アプリケーション構築の一環としてこのコンポーネントの機能を使いたくなる理由が説明されています。

== link:win-windesktopalert-using-windesktopalert.html[WinDesktopAlert の使用]

このセクションは、WinDesktopAlert コントロールによって提供されるさまざまな特徴や機能を効率的に使用するための手助けとなるタスクベースの情報のゲートウェイです。

== link:windesktopalert-api-overview.html[API 概要]

このトピックでは、WinDesktopAlert コンポーネントを使用してプログラミングするときに取り扱う名前空間とクラスのリストを掲載しています。本トピックでリストされている名前空間とクラスは、{ProductName} ヘルプの「API リファレンスガイド」にリンクしています。