////

|metadata|
{
    "name": "windockmanager-about-windockmanager",
    "controlName": ["WinDockManager"],
    "tags": [],
    "guid": "{72962E85-EE8E-4C60-9A93-4D9B372FBA8E}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= WinDockManager について

WinDockManager の主な機能の一覧を次に示します。

* ドッキングとフローティングが可能なウィンドウ -- Microsoft Visual Studio.Net と同じように、コントロールをホスト コンテナの任意の端にドッキングしたり、独自のフローティング ウィンドウに表示したりできます。
* 自動表示のサポート -- ドッキングされたコントロールをピン解除表示することで、画面領域を節約できます。ピン解除されたコントロールは、コンテナの外側に沿った領域にタブで表されます。タブを選択すると、コントロールがスライドアウトする個別のウィンドウに表示されます。
* 状態の切り替え -- ペインのキャプション、タブ項目またはスライド グループのヘッダをダブルクリックすることでペインのドック状態を切り替えることができます。
* マルチ グループ スタイル -- ドッキング可能コントロール同士を、ドッキングまたはフローティングされているときに任意の組み合わせでグループ化できます。UltraDockManager は、水平分割、垂直分割、タブ グループ、およびスライド グループの 4 つのグループ スタイルをサポートしています。
* デザインタイムの完全な WYSIWYG 機能 -- ドッキング可能コントロールをデザインタイムに簡単に作成して配置できます。コントロールを選択すると、Visual Studio のプロパティ グリッドで個々のドックされたコントロールの設定にアクセスできます。
* 保存およびロード -- ドッキングされたウィンドウのレイアウトをデザインタイムおよびランタイムに保存およびロードできます。
* 階層的なコントロール設定 --　ドッキングされたコントロールの設定は、個々のペイン、グループ内の子ペイン、またはすべてのペインについて設定できます。
* Window スタイル -- ひとつの WindowStyle プロパティが、キャプションやタブスタイルを含むペイン ウィンドウのデフォルトの外観に作用します。各設定は、ペインの設定やグループの設定を通じてさらに詳細に制御できます。また、LayoutStyle プロパティは、ドック領域のペインがフォームのクライアント領域をどのように管理するのかを指定するためにも使用できます。
* ペインのグループ化と移動 -- ドック コントロールが作成されたら、ペインのキャプション、タブ項目またはスライド グループのヘッダをクリックして移動することができます。
* ドックの禁止 -- ペインをドラッグして移動時、CTRL キーを押しながらドロップした場合、ペインは常にフロート ウィンドウになります。
* コントロールの削除およびドックの解除 -- ドックされたコントロールをドック可能なウィンドウから切り取り、削除またはドラッグした場合、関連付けられた DockableControlPane は削除されます。ドック コントロールのドックの解除は、ドックされたコントロールを右クリックしてコンテキスト メニューで [コントロールのドック] をクリックすることでも可能です。