////

|metadata|
{
    "name": "windockmanager",
    "controlName": ["WinDockManager"],
    "tags": [],
    "guid": "{B8FD6A58-FEE1-439A-8281-18BCE2A5E13E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinDockManager

WinDockManager コンポーネントに関連した概要/タスクベースの情報のすべてが収められている領域を探しているのであれば、このページをご覧ください。このセクションには、WinDockManager コンポーネントに関する貴重な情報が含まれています。WinDockManager コンポーネントの機能やアプリケーションでこれを使いたくなる理由から、このコンポーネントを使って共通タスクを実行する際のステップごとの手順に至るまで豊富にあります。

以下のリンクをクリックすると、WinDockManager コントロールに関する重要な情報にアクセスします。

== link:windockmanager-understanding-windockmanager.html[WinDockManager の理解]

このセクションでは、WinDockManagerコンポーネントの機能をより良く理解するために助けとなるあらゆる情報や、アプリケーション構築の一環としてこのコンポーネントの機能を使いたくなる理由が説明されています。

== link:windockmanager-getting-started-with-windockmanager.html[WinDockManager で開始]

WinDockManager コントロールを使った処理をできるだけ早く準備、実行できるように、WinDockManager コンポーネントの利用を開始する方法（WinDockManager のフォームへの追加など）を提供しています。

== link:win-windockmanager-using-windockmanager.html[WinDockManager の使用]

このセクションは、WinDockManager コントロールによって提供されるさまざまな特徴や機能を効率的に使用するための手助けとなるタスクベースの情報のゲートウェイです。

== link:windockmanager-api-overview.html[API 概要]

このトピックでは、WinDockManager コンポーネントを使ってプログラミングする際に操作しなければならない名前空間とクラスをリストします。本トピックでリストされている名前空間とクラスは、{ProductName} ヘルプの「API リファレンスガイド」にリンクしています。