////

|metadata|
{
    "name": "winformattedtexteditor-add-items-to-winformattedtexteditors-context-menu",
    "controlName": [],
    "tags": ["FAQ","How Do I"],
    "guid": "{1002F353-C88D-4A2B-B11D-F188C5348378}",  
    "buildFlags": [],
    "createdOn": "2006-12-09T13:25:29Z"
}
|metadata|
////

= WinFormattedTextEditor のコンテキスト メニューに項目を追加

WinFormattedTextEditor を含み、コントロールのそれぞれにコンテキスト メニューを追加できます。WinFormattedTextEditor がより便利になった点は、項目を追加できるコンテキスト メニューに組み込まれていることです。これらの pick:[win-forms="link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.formattedlinklabel.ultraformattedtexteditor~contextmenuitems.html[ContextMenuItems]"]  には、切り取り、コピー、および貼り付けなどのダイアログ、クリップボード操作、太字、斜体、および下線などのフォーマッティング操作を含むことができます。

デザイン タイムにコンテキスト メニューを修正するには、 WinFormattedTextEditor が選択されており、[プロパティ] ウィンドウに ContextMenuItems プロパティがあることを確認してください。ドロップダウン矢印をクリックし、コンテキスト メニューに表示したい項目を選択します。

以下のコードは、コンテキスト メニューに太字、斜体、および下線項目を追加する方法を示しています。これらのメニュー項目は、テキストが選択された時に表示されます。それぞれの項目をクリックすると、選択されたテキストにスタイルが追加されます。

*Visual Basic の場合：*

----
Imports Infragistics.Win.FormattedLinkLabel
...
Me.UltraFormattedTextEditor1.ContextMenuItems = (FormattedTextMenuItems.Bold |_
  FormattedTextMenuItems.Italics | FormattedTextMenuItems.Underline)
----

*C# の場合：*

----
using Infragistics.Win.FormattedLinkLabel;
...
this.ultraFormattedTextEditor1.ContextMenuItems = (FormattedTextMenuItems.Bold |
  FormattedTextMenuItems.Italics | FormattedTextMenuItems.Underline);
----