////

|metadata|
{
    "name": "winformattedtexteditor-display-winformattedtexteditors-support-dialog-boxes",
    "controlName": [],
    "tags": ["How Do I"],
    "guid": "{360C71EB-7C04-4AAA-B599-A14AD3589BC0}",  
    "buildFlags": [],
    "createdOn": "2006-12-09T13:29:33Z"
}
|metadata|
////

= WinFormattedTextEditor のサポート ダイアログ ボックスを表示

WinFormattedTextEditor には 3 つのサポート ダイアログ ボックスがあり、ドキュメントのフォーマッティングでエンド ユーザーを支援します。これらのダイアログ ボックスは、エンド ユーザーがpick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~showfontdialog.html[Fonts]"] 、pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~showimagedialog.html[Images]"] 、および pick:[win-forms="link:{ApiPlatform}win{ApiVersion}~infragistics.win.formattedlinklabel.formattedtexteditinfo~showlinkdialog.html[Hyperlinks]"]  をフォーマットする支援を行います。WinFormattedTextEditor にはユニークなコンテキスト メニューがあり、エンド ユーザーはこれらのダイアログ ボックスを起動できますが、ボタン（おそらくツールバー）からこれらのダイアログ ボックスを起動することが必要な場合もあります。

以下のコードは、[フォント] ダイアログ ボックスを開く方法を示しています。アプリケーションのロジックに適するクリック イベントまたは特別なメソッドにこのコードを配置できます。

*Visual Basic の場合：*

----
Me.UltraFormattedTextEditor1.EditInfo.ShowFontDialog()
----

*C# の場合：*

----
this.ultraFormattedTextEditor1.EditInfo.ShowFontDialog();
----