////

|metadata|
{
    "name": "winflowlayoutmanager-about-winflowlayoutmanager",
    "controlName": [],
    "tags": ["Getting Started","Layouts"],
    "guid": "{E75B6135-F0E4-4DEE-A05D-6936EE775A94}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinFlowLayoutManager について

WinFlowLayoutManager エレメントは、コントロールを配置するためのコンポーネントです。これを使用すると、フォーム上にコントロールを配置するためのコードを記述する必要がありません。フォーム上のコントロールの位置は、コントロールのサイズと以下の設定により決定されます。

* Alignment - コントロールの方向に対してコントロールの配置を決定します。
* HorizontalGap - 各コントロール間およびコンテナとコントロールの境界線との間の水平方向のピクセル数。
* Margins - 格納しているコントロールと格納されているコントロールの境界線間の最小距離。
* Orientation - コントロールが垂直方向または水平方向のどちらに配列するかを決定します。
* VerticalGap - 各コントロール間およびコンテナとコントロールの境界線との間の垂直方向のピクセル数。
* WrapItems - スペースが限られていて 1 行で配置できない場合、項目が改行に折り返すかどうかを設定します。

上記の設定のほかに、UltraFlowLayoutManager は操作するコントロールにエクステンダ プロパティを付加します。このプロパティでは、個々のコントロールがそのコントロールに適用されるレイアウト関連の情報を指定できます。エクステンダ プロパティには次の 2 つがあります。

* IncludeInLayout - コントロールの位置をレイアウト マネージャが管理するかどうかを決定します。
* PreferredSize - レイアウト マネージャが使用するコントロールのサイズを指定します。