////

|metadata|
{
    "name": "wingridbaglayoutmanager-about-wingridbaglayoutmanager",
    "controlName": [],
    "tags": ["Getting Started","Layouts"],
    "guid": "{90920459-F9A0-4EB6-A693-1CC8893139E8}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinGridBagLayoutManager について

WinGridBagLayoutManager エレメントは、コンテナ（たとえばフォーム）内のコントロールのための柔軟な自動配置およびサイズ変更機能を提供します。このコンポーネントは、論理列と論理行の概念を使用して、管理対象のさまざまなコントロールの相対的な配置およびサイズ変更を簡単に指定する簡単な方法を提供します。コンテナ内のコントロールの位置とサイズは、次の設定によって決まります。

* ExpandToFitHeight - 操作対象のすべてのコントロールの高さを全体の高さと合わせて自動調整するかどうかを設定します。
* ExpandToFitWidth - 操作対象のすべてのコントロールの幅を全体の幅と合わせて自動調整するかどうかを設定します。
* Margins - 格納しているコントロールと格納されているコントロールの境界線間の最小距離。

上記の設定のほかに、UltraGridBagLayoutManager は操作するコントロールにエクステンダ プロパティを付加します。このプロパティでは、個々のコントロールがそのコントロールに適用されるレイアウト関連の情報を指定できます。エクステンダ プロパティには次の 2 つがあります。

* GridBagConstraint - レイアウト マネージャのコントロールに対する効果を調整するための多くのプロパティが含まれます。
* IncludeInLayout - コントロールの位置をレイアウト マネージャが管理するかどうかを決定します。
* MinimumSize - コントロールのサイズ変更で許される最大サイズを指定します。
* PreferredSize - レイアウト マネージャが使用するコントロールのサイズを指定します。