////

|metadata|
{
    "name": "wingriddocumentexporter-change-the-paper-orientation-and-size",
    "controlName": ["WinGridDocumentExporter"],
    "tags": [],
    "guid": "{4DB5AE4A-ED5C-4BB4-B177-0556E03782B7}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 用紙の方向とサイズを変更

WinGridDocumentExporter™ によって、 link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~targetpaperorientation.html[TargetPaperOrientation] プロパティを使用してポートレート（デフォルト）から風景に用紙の向きを変更することができます。このプロパティは、WinGrid™ が風景の向きに適する、またはレポートが風景の向きに既に設定されている場合に役立ちます。

TargetPaperOrientation プロパティと共にタンデムで使用できる役立つプロパティが link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~targetpapersize.html[TargetPaperSize] プロパティです。TargetPaperSize プロパティは、アスペクト比および用紙の最小サイズを制御しますが、用紙のサイズは直接制御しません。WinGridDocumentExporter はグリッドの幅に基づいて用紙のサイズを自動調整します。 link:{ApiPlatform}documents.reports{ApiVersion}~infragistics.documents.reports.report.pagesizes.html[PageSizes] クラスで事前に定義したページ サイズ（たとえば、レター、リーガル）に TargetPageSize プロパティを設定できます。

以下のコードを使用して、ページの向きを風景に、ページ サイズをリーガルに設定します。

*Visual Basic の場合：*

----
Me.UltraGridDocumentExporter1.TargetPaperOrientation = _
	Infragistics.Documents.Reports.Report.PageOrientation.Landscape
Me.UltraGridDocumentExporter1.TargetPaperSize = _
	New Infragistics.Documents.Reports.Report.PageSizes.Legal
----

*C# の場合：*

----
this.ultraGridDocumentExporter1.TargetPaperOrientation =
	Infragistics.Documents.Reports.Report.PageOrientation.Landscape;
this.ultraGridDocumentExporter1.TargetPaperSize =
	new Infragistics.Documents.Reports.Report.PageSizes.Legal;
----