////

|metadata|
{
    "name": "wingriddocumentexporter-export-wingrid-to-a-new-pdf-document",
    "controlName": ["WinGridDocumentExporter"],
    "tags": ["Exporting"],
    "guid": "{C04D2C08-997E-451B-AD08-D61BE63726F3}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinGrid を新しい PDF ドキュメントにエクスポート

WinGridDocumentExporter™ コンポーネントによって、WinGrid™ 全体を PDF または XML Paper Specification (XPS) ドキュメントに直接エクスポートすることができます（ link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.gridexportfileformat.html[GridExportFileFormat] プロパティに基づいて）。 link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter.html[UltraGridDocumentExporter] オブジェクトの link:{ApiPlatform}win.ultrawingrid.documentexport{ApiVersion}~infragistics.win.ultrawingrid.documentexport.ultragriddocumentexporter~export.html[Export] メソッドを呼び出すだけでこれを実行できます。Export メソッドには、エクスポート プロセスをカスタマイズするためのオーバーロードがいくつか含まれています。このトピックは、4 つめのオーバーロードについて検討します。このオーバーロードは、3 つのパラメータを受け付けます。

* エクスポートする WinGrid（Infragsitics.Win.UltraWinGrid.UltraGrid）
* WinGrid がエクスポートされるドキュメントのファイル名（System.String）
* ドキュメントのファイル フォーマット（Infragistics.Win.UltraWinGrid.DocumentExport.GridExportFileFormat）

このトピックは、フォーム上にデータ バインドされた WinGrid コンポーネントおよび WinGridDocumentExporter コンポーネントがあることが前提となっています。WinGrid のデータ ソースへのバインディングの詳細は、 link:wingrid-binding-wingrid-to-a-flat-data-source-clr2.html[「WinGrid をフラット データ ソースにバインドする」]を参照してください。

以下のコードを使用して、WinGrid を PDF ドキュメントにエクスポートします。このコードは、PDF ドキュメントに "WinGrid_Report.pdf" という名前を指定し、C:\Reports フォルダに配置します。

*Visual Basic の場合：*

----
Me.UltraGridDocumentExporter1.Export( _
	Me.UltraGrid1, _
	"C:\Reports\WinGrid_Report.pdf", _
	Infragistics.Win.UltraWinGrid.DocumentExport.GridExportFileFormat.PDF)
----

*C# の場合：*

----
this.ultraGridDocumentExporter1.Export(
	this.ultraGrid1,
	"C:\\Reports\\WinGrid_Report.pdf",
	Infragistics.Win.UltraWinGrid.DocumentExport.GridExportFileFormat.PDF);
----