////

|metadata|
{
    "name": "wingrid-row-layouts",
    "controlName": ["WinGrid"],
    "tags": ["Grids","Layouts"],
    "guid": "{C3BF9EA6-6B9E-491F-B3A4-415C3C4CC570}",  
    "buildFlags": [],
    "createdOn": "2005-11-07T00:00:00Z"
}
|metadata|
////

= 行レイアウト

行レイアウトは、アプリケーション内の WinGrid の書式を柔軟にデザインする手段を提供します。行レイアウトを使用すると、データを表示および入力するためのフォーム型の外観を作成できます。スタイルには、一般的な行表示スタイルとカード ビュー スタイルの両方を使用できます。

== 通常ビューとカード ビュー

行レイアウト機能では、データセルとそのラベルの位置関係を設定できます。ラベルがこのデータ セルに相対してどのように表示するのかは、その他の設定と組み合わせて表示のタイプによって通常決定されます。通常（グリッド行）ビューで、データ ラベルは列ヘッダーの形式でデータ セルの上に表示します。カードビューでは、データラベルはデータセルの左に表示されます。ラベルとデータの近さは、他の設定の影響を受ける場合があります。たとえばカードビューでは、CardStyle 設定として「MergedLabels」を選択した場合、このプロパティを他の設定にした場合よりも、データラベルがデータの左側のより遠い位置に配置されます。しかし、位置設定の一般的な原則は変わりません。

== ラベルの配置

行レイアウトでは、このセルとラベルの関係についてさらに多くの点を変更できます。データラベルは、関係するデータの上下左右いずれにも配置できます。ラベルをデータのそばに保つことも、ラベル同士をまとめることも可能です。さらに重要なことは、カスタムの高さ、幅、および配置を使用してセルとラベルを独立してサイズ設定および配置することができます。これによってセルはレイアウトで複数の列にスパンすることができます。

== レイアウトのリサイズ

行レイアウトのもう１つの重要な機能は、サイズと位置を、（絶対的にではなく）相対的に指定できることです。通常、WinGrid はレイアウトを動的に調整して、使用可能な画面領域内で指定した配置に合わせます。サイズは基本設定として指定され、ユーザーの操作に従ってレイアウトを変更するときに、可能であれば WinGrid が使用されます。重要なデータが常に読みやすいように、最小サイズを指定できます。 また、サイズ変更の際、レイアウト内の重要性の高いデータが優先されるように、各セルの相対的な重みを指定することもできます。

WinGrid コントロール内の行レイアウトの詳細は以下のトピックを読んでください。

* link:wingrid-using-row-layouts-designer.html[行レイアウト デザイナの使用]
* link:wingrid-advanced-row-layouts-part-1-of-2.html[高度な行レイアウト（1/2）]
* link:wingrid-advanced-row-layouts-part-2-of-2.html[高度な行レイアウト（2/2）]
* link:wingrid-working-with-row-layouts.html[行レイアウトの操作]
* link:wingrid-grouping-columns-in-row-layout-mode-using-the-designer.html[デザイナを使用して行レイアウト モードで列をグループ化]
* link:wingrid-grouping-columns-in-row-layout-using-code.html[コードを使用して行レイアウトで列をグループ化]
* link:wingrid-collapsing-column-groups.html[列グループの縮小]