////

|metadata|
{
    "name": "winmonthviewmulti-api-overview",
    "controlName": ["WinMonthViewMulti"],
    "tags": [],
    "guid": "{0B963407-CDC0-4472-8456-0883BDCC0385}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API 概要

このセクションはコントロールに関連する各名前空間をリストします。また、このコントロールでプログラミングをする時に使用するいくつかのキー クラスも示します。このページの名前空間とクラスは、Infragistics の API ドキュメントに直接リンクされています。

=== WinMonthViewMonth 名前空間：

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.monthviewmulti_namespace.html[Infragistics.Win.UltraWinSchedule.MonthViewMulti]"]

=== キー クラス:

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.monthviewmulti.calendardropdownbuttonuielement.html[CalendarDropDownButtonUIElement]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.monthviewmulti.dayuielement.html[DayUIElement]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.monthviewmulti.monthuielement.html[MonthUIElement]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.monthviewmulti.weekuielement.html[WeekUIElement]"]