////

|metadata|
{
    "name": "winnavigationbar-comparing-winnavigationbar-to-wintree-and-winlistview",
    "controlName": ["WinNavigationBar"],
    "tags": ["Navigation","Patterns and Practices"],
    "guid": "{F8C904BC-C696-4244-BD36-68C9ABCA50F5}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinNavigationBar を WinTree と WinListView で比較

WinTree™ および WinListView™ は、この数年間ファイル システム参照のユーザー インターフェイスを支配しています。ユーザーはファイル システムをナビゲートするためにいずれかのコントロールを使用できます。これらのコントロールへのマイナス面は、使用できる画面領域の約半分がコントロールによって使用される可能性があることです。画面領域は貴重であるので、使用する画面領域を減らし同じ結果で同じアクションを実行するためのより良い方法が必要になります。WinNavigationBar コントロールは、WinTree および WinListView と同じ作業を達成できますが、Microsoft Internet Explorer などのアプリケーションでアドレス バーが使用するのと同じ量の画面領域を使用します。

== WinNavigationBar と WinTree

WinTree は、TOC またはファイル システムなどの階層的なデータ モデルを表示するための優れたコントロールです。アプリケーションが求める項目のグループ化のタイプに対して WinTree を使用できます。ノードを動的にロードして、システム リソースを節約し、アプリケーションを全体的にスピードアップすることができます。ただし、ツリーを使いやすくするには、エンド ユーザーがスクロールしすぎないように垂直方向の領域を十分にとる必要があります。つまり、WinTree は通常アプリケーション ウィンドウの左側でドックされます。ドックされると、WinTree は画面領域のほぼ半分を使用する可能性があります。これは必ずしもマイナス面ではありませんが、より良い方法である WinNavigationBar を推奨します。

WinNavigationBar はアプリケーション ウィンドウの上部という理想的な場所に配置されますが、使用する領域は標準のテキスト ボックス程度です。WinNavigationBar コントロールの独自性は、WinTree-type コントロールであることですが、ユーザーが現在見ていないすべての無関係なノードがありません。WinNavigationBar は、ボタン上にテキストが付いた複数のドロップダウン ボタンで構成されます。これらのボタンのそれぞれをツリーのノードにマップできます。ドロップダウン ボタンをクリックすると、子の位置のリストが表示します。これらの子の位置は、ノードの子と考えることができます。子の位置（ノード）を選択すると、単一の位置がそのパス上の最後に配置されます。

== WinNavigationBar と WinListView

WinListView は単に項目のコンテナです。WinListView はいくつかの異なる方法で項目を表示できます。ファイル システム ブラウザとして WinListView を使用すれば、アイコンのコレクションまたはリストでファイルおよびフォルダをファイリングできます。そのリストはアプリケーションが必要とするのと同程度のシンプルまたは詳細なリストとなります。ファイル システムを参照する時、WinTree とは逆で WinListView コントロールが非常に必要になります。WinListView はエンド ユーザーのナビゲーションの最終結果を表示します。現在のナビゲーション パスのファイルとフォルダのみが表示されます。これについては、WinListView を WinNavigationBar よりも実用的にするのはファイルです。

WinNavigationBar はナビゲーション インタフェースであり、ファイル システムのフォルダなどの階層的な構造を表示する時にこのコントロールの使用は最適です。ただし、ファイルの表示はナビゲーションの目的を損ないます。終わりに来ると、それ以降のナビゲーションがないからです。WinListView などのリスト表示の仕組みでファイル参照を支援できるのはこの点です。WinNavigationBar のボタンのひとつのドロップダウン リストにすべてのフォルダのファイルをリストすることは実用的でない場合もあります。