= WinPeekPopup の使用

WinPeekPopup™ は、ユーザーに豊富な機能を提供しつつ、画面のスペースを節約する方法を提供します。このコンポーネントを使用すると、アプリケーションのインターフェイスの一部を、コマンド ボタンなどの単一のコントロールに表すことができます。ボタンをクリックすると、インターフェイスを構成するコントロールを表示するコンテナーが開きます。

WinPeekPopup はデザイン タイムにユーザー インターフェイスを表示しません。Content プロパティを使用して、ポップアップ コントロールとして表示するコントロールを割り当てます。

.注:
[NOTE]
====
このコントロールは、フォームまたは他のコントロールを含む Panel などのコンテナー コントロールにすることができます。
====

ランタイムに `Show()` メソッドを呼び出して、WinPeekPopup のコンテンツを現在のマウス位置または指定した位置に表示します。

== WinPeekPopup を使用した作業の開始

`WinPeekPopup` をフォームですばやく実行するために、次の手順を実行します
[start=1]
. Visual Studio ツールボックスで WinPeekPopup コンポーネントをダブルクリックします。ダブルクリックされたコンポーネントがフォームのコンポーネント トレイ エリアに追加されます。
[start=2]
. ポップアップとして表示するコントロールを追加するか、フォームに既に存在することを確認します。このコントロールは、他のコントロールを含む Panel などのコンテナー コントロールにすることができます。また、フォームそのものでも使用できます。
[start=3]
. WinPeekPopup コンポーネントを選択し、プロパティ グリッドで Content プロパティを探します。ポップアップ コンテナーとして使用されるコントロールをドロップダウン リストから選択します。
[start=4]
. ポップアップ コンテナーを表示するフォームにコントロールを追加します。通常、ボタン コントロールです。

.注:
[NOTE]
====
フォーム自体をポップアップ コンテナーとして選択した場合は、ポップアップを表示するための UI を別のフォームに配置し、クロスフォーム参照を考慮に入れて必要に応じてコードを変更します。
====

[start=5]
. ポップアップを表示するボタン (または他のコントロール) の Click イベントに次のコードを追加します。

*Visual Basic の場合:*
----
Private Sub btnShowTree_Click(ByVal sender As Object, _
  ByVal e As System.EventArgs) Handles btnShowTree.Click
	Me.UltraPeekPopup1.Show()
End Sub
----

*C# の場合:*
----
private void btnShowTree_Click(object sender, EventArgs e)
{
	this.ultraPeekPopup1.Show();
}
----

[start=6]
. プロジェクトをビルドして実行します。フォームが表示されると、ポップアップとして指定したコントロールが非表示になります。ボタンをクリックすると、マウスの現在の位置にポップアップ コントロールが表示されます。ポップアップのコンテナー コントロールを使用した場合は、コンテナー内の任意のコントロールをクリックするか、コンテナーの任意の場所をクリックすると、ポップアップが画面上に残ります。ポップアップ コントロールの外側をクリックすると、閉じられます。