////

|metadata|
{
    "name": "winpivotgrid-glossary",
    "controlName": [],
    "tags": [],
    "guid": "45fe090b-6a63-44c6-9adb-bef02341f0da",  
    "buildFlags": [],
    "createdOn": "2014-03-13T21:33:49.6257528Z"
}
|metadata|
////

= 用語集

=== はじめに

このセクションは、ピボット グリッドのトピックでよく使用される用語を説明します。

=== 用語の定義

[options="header", cols="a,a"]
|====
|用語|定義

|ディメンション
|ディメンションはメンバーと呼ばれるハイパーキューブの構造属性です。すべてのメンバーはデータの同様なカテゴリに属します。 

たとえば、時間ディメンションは年、四半期、月などです。また、市および国は地域ディメンションになります。 

ディメンションは、多次元の配列で値を識別するインデックスとして操作します。取得、検索、解析のためにデータを構成して選択する方法を提供します。ディメンションは、レポートの行と列に表示されるパラメーターです。

|階層
|階層は親/子の関係を表します。ディメンションのメンバーを親/子の関係を定義する論理ツリー構造に体系化する方法です。 

たとえば、年は四半期の親で、四半期は月の親です。ディメンションのメンバーを階層に配置する場合、OLAP モデルはディメンションのメンバーを集計します。子メンバーの値は親メンバーに自動的に集計されます。

|ハイパーキューブ
|ハイパーキューブは、1 つ以上のディメンションを含むデータの配列です。 

ハイパーキューブは 3 次元のグリッドです。たとえば、会社は予算経費を比較するために財務データを製品、時間、市によって集計できます。製品、時間、市、およびシナリオ (予算) は財務データのディメンションです。

|レベル (階層)
|階層を持つディメンションのメンバーは、そのメンバーの階層が単一のパスに同じ子孫の数がある場合に同じレベルにあります。 

==== 例 1 

(パスは __イタリック_ です_ ): 

Dimension1 は _[Parent1].[Child1].[Child2]_ を含みます。 

Dimension2 は _[Parent1].[Child1].[Child2]_ を含みます。 

パスの子孫の数は同じので、両方のディメンションは同じ階層レベルにあります。 

==== 例 2 

(パスは __イタリック_ です_ ): 

Dimension1 は _[Parent1].[Child1].[Child2]_ を含みます。 

Dimension2 は _[Parent1].[Child1].[Child2].[Child3]_ を含みます。 

この例で、Dimension2 のパスは Dimension1 より子孫があり、階層のレベルは異なります。

|メンバー (ディメンション)
|メンバーはディメンション内の値の結合です。 

例: _[Date].[2014]_ _[Date].[2014].[July]_ _[Date].[2014].[July].[4th]_ 

上の各ディメンションはメンバーです。「All Members」と呼ばれる特別なメンバーがあります。 

たとえば、 _[All Periods]_ はすべてのメンバーに適用します。

|メジャー
|メジャーは数値です。数値入力列および集計された値または統計の結合が可能です。クエリされた行/列の返された値です。メジャーは、集計されているデータ ソースから読み込まれます。1 つの入力列は 1 つ以上のメジャーを読み込む可能性があります。たとえば、「Amount」のメジャーを表示するか、「Amount」の入力列から「Sum of Amount」および「Maximum of Amount」のメジャーを計算できます。

|オンライン解析処理 (OLAP)
|オンライン解析処理 (OLAP) は、多次元データ キューブから複雑な解析クエリの応答を取得するメソッドです。 

OLAP はビジネス インテリジェンスで使用されます。関係レポートおよびデータ マイニングに関連付けられます。ただし、OLAP のデータベースは多次元データ モデルを使用します。ユーザーは短い実行時間で解析レポートを実行できます。 

OLAP データ モデルで、情報は量値 (メジャー) および説明カテゴリ (ディメンション) を含むキューブとして操作されます。

|====

== 関連コンテンツ

=== トピック

以下のトピックでは、このトピックに関連する追加情報を提供しています。

[options="header", cols="a,a"]
|====
|トピック|目的

| link:winpivotgrid.html[WinPivotGrid]
|このセクションは、Infragistics® Windows Forms® の WinPivotGrid™ コントロールについてのトピックを含みます。

|====

=== リソース

以下の資料 (Infragistics のコンテンツ ファミリー以外でもご利用いただけます) は、このトピックに関連する追加情報を提供します。

[options="header", cols="a,a"]
|====
|タイトル|目的

| link:http://ja.wikipedia.org/wiki/OLAP[OLAP]
|OLAP キューブの用語を提供します。

|====