////

|metadata|
{
    "name": "winstatusbar-set-the-panel-style-to-cursorposition",
    "controlName": ["WinStatusBar"],
    "tags": ["How Do I"],
    "guid": "{33C8053D-A3B8-437D-92C9-2D604EACFF9E}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= パネル スタイルを CursorPosition に設定

WinStatusBar の CursorPostion スタイルは、パネルの Control プロパティによって示されるコントロール内での現在の X 座標と Y 座標を表示するパネルです。

CusrosorPosition スタイルのパネルをデザインタイムに設定するには：

[start=1]
. UltraStatusBar を Windows Formsに追加します。
[start=2]
. プロパティ ページで、Panels プロパティまで下にスクロールします。省略ボタンをクリックして pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanelscollection.html[Panels]"]  コレクションを表示します。
[start=3]
. [追加] ボタンをクリックします。これで、新しいパネルが追加されます。
[start=4]
.pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~style.html[Style]"]  プロパティが表示されるまでプロパティをスクロールします。Style プロパティを「CursorPosition」に設定します。
[start=5]
. Control プロパティを、このパネルで反映するコントロールに設定します。有効なインスタンス化されたコントロールはこのドロップダウン リストないに表示されます。
[start=6]
. [OK] をクリックしてウィンドウを閉じると、CursorPosition パネルがステータスバーに追加されます。

ランタイムに

*Visual Basic の場合：*

----
Imports Infragistics.Win.UltraWinStatusBar
...
Private Sub WinStatusBarQuickTourCursorPositionPanel_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	' 新しいパネルを作成します
	Dim myPanel As New UltraStatusPanel()
	' パネルのスタイルを設定します
	myPanel.Style = PanelStyle.CursorPosition
	' デフォルトのテキストを設定します
	myPanel.Text = "CursorPosition"
	' エレメントにパネルを追加します
	Me.UltraStatusBar1.Panels.Add(myPanel)
	' 文字の位置が反映されるコントロールを指定します
	Me.UltraStatusBar1.Panels(0).Control = Me.UltraTextEditor1
End Sub
----

*C# の場合：*

----
using Infragistics.Win.UltraWinStatusBar;
...
private void WinStatusBarQuickTourCursorPositionPanel_Load(object sender, System.EventArgs e)
{
	// 新しいパネルを作成します
	UltraStatusPanel myPanel = new UltraStatusPanel();
	// パネルのスタイルを設定します
	myPanel.Style = Infragistics.Win.UltraWinStatusBar.PanelStyle.CursorPosition;
	// デフォルトのテキストを設定します
	myPanel.Text = "CursorPosition";
	// エレメントにパネルを追加します
	myPanel.Text="CursorPosition";
	ultraStatusBar1.Panels.Add(myPanel);
	// 文字の位置が反映されるコントロールを指定します
	this.ultraStatusBar1.Panels[0].Control = this.ultraTextEditor1;
}
----