////

|metadata|
{
    "name": "winstatusbar-panel-styles",
    "controlName": ["WinStatusBar"],
    "tags": ["Styling"],
    "guid": "{8469ACBC-CE86-4E86-9FF5-66A9DE070AC3}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= パネル スタイル

WinStatusBar は 13 のパネル スタイルを提供します。

== AutoStatusText

UltraStatusBar は拡張機能を提供するコンポーネントで、フォームのすべての Control、またはステータスバーを格納しているすべての UserControl に対して、追加のプロパティ（「StatusBarText」）を提供します。このプロパティは Windows Formsの MenuItem コンポーネントにも提供されます。StatusBarText は、マウスがコントロールの範囲上を移動したとき、またはメニュー項目が選択されたときに表示されるテキストを制御する、テキスト プロパティです。AutoStatusText パネル スタイルは、Internet Explorer でマウスがリンクやメニュー項目上を移動したときに見られるものと同様の機能を提供します。

[NOTE]
====
*注:* コントロールは MouseEnter および MouseLeave の通知を利用します。そのため、別のコントロールによって完全に覆われているコントロールに対して設定した場合、プロパティの効果がないように見えることがあります。これは、マウスが子コンポーネント上を移動するときに MouseLeave イベント通知が発生するためです。これらのコントロールに対するステータス テキストを提供するには、子コントロールに対してプロパティを設定するか、または実行時にステータスバー コントロールの Get または Set メソッド（つまり SetStatusBarText）を使用する必要があります。
====

== Button

標準のプッシュ ボタンをステータスバーに表示します。Button には画像とテキストを表示でき、クリックするとステータスバー コントロールの PanelButtonClick イベントが呼び出されます。

== Character Position（文字位置）

関連付けられた RichTextBox コントロールの現在の行と文字の位置を表示します。RichTextBox は Control プロパティの設定によってパネルに関連付けられます。パネルの CharacterPositionFormat を使用すると形式を変更できます。また、このスタイルのパネルをダブルクリックすると Visual Studio と同様のダイアログが表示され、エンド ユーザーは関連付けられた RichTextBox の中の特定の行に移動できます。

== Cursor Position（カーソル位置）

マウスが Control の範囲上を移動したときに、関連付けられたコントロールに対して相対的な X および Y 座標を表示します。

== Control Container（コントロール コンテナ）

ControlContainer スタイルのパネルは、パネルのサイズと位置に基づいて、関連付けられた Control の親と位置を変更します。

== Date

パネルの DateTimeFormat プロパティを使用して、現在の日付を表示します。デフォルトでは、日付は現在のカルチャの短い日付形式を使用して書式設定されます。

== KeyState

NumLock、Insert、ScrollLock、Caps Lock などのキーを含む、選択されたキーの状態を表示します。パネルは、キーが切り替えられていないときに OnText を無効として表示するか、または異なる文字列を表示できるように設定できます。パネルの KeyStateInfo プロパティは、このスタイルのパネルに対して追加のプロパティを提供します。

== Marquee（マーキー）

パネルのテキストと画像をマーキー スタイルのアニメーションで表示します。パネルは、スクロール、スライド、バウンド、フラッシュ、タイピングの、5 種類のマーキー アニメーションをサポートしています。パネルの MarqueeInfo プロパティは、このスタイルのパネルに対して追加のプロパティを提供します。

== MDIList

UltraStatusBar を格納しているフォームの個々の MDI 子フォームに対して状態ボタンを表示します。状態ボタンをクリックすると、そのボタンに関連付けられた子フォームがアクティブになります。

== Progress

プログレスバーをパネルに表示します。このパネルは、UltraProgressBar で使用できるものと同じプロパティの多くを、パネルの ProgressBarInfo プロパティを通じて公開しています。

== State Button

切り替え型のボタンをパネルに表示します。パネルの Checked プロパティは、状態ボタンが押されているかどうかを示します。ボタンをクリックすると状態が自動的に設定され、PanelButtonClick イベントが呼び出されます。

== Text

画像とテキストをパネルに表示します。

== Time

パネルの DateTimeFormat プロパティを使用して、現在の時刻を表示します。デフォルトでは、時刻は現在のカルチャの短い時刻形式を使用して書式設定されます。