////

|metadata|
{
    "name": "winstatusbar-set-the-panel-style-to-text",
    "controlName": ["WinStatusBar"],
    "tags": ["How Do I","Styling"],
    "guid": "{5CC5CE5D-1418-400E-9AE3-AA0FDE315493}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= パネル スタイルを Text に設定

Text パネルは、標準のラベルまたは静的なテキスト領域として機能する、WinStatusBar 上の単純なパネルです。

Text スタイルのパネルをデザインタイムに設定するには：

[start=1]
. WinStatusBar を Windows Formsに追加します。
[start=2]
. プロパティ ページで、Panels プロパティまで下にスクロールします。省略ボタンをクリックして pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanelscollection.html[Panels]"]  コレクションを表示します。
[start=3]
. [追加] ボタンをクリックします。これで、新しいパネルが追加されます。
[start=4]
.pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~style.html[Style]"]  プロパティが表示されるまでプロパティをスクロールします。Style プロパティを Text に設定します。
[start=5]
.pick:[win-forms="link:{ApiPlatform}win.ultrawinstatusbar{ApiVersion}~infragistics.win.ultrawinstatusbar.ultrastatuspanel~text.html[Text]"]  プロパティに、このステータス バー パネルに表示する値を設定します。
[start=6]
. [OK] をクリックしてウィンドウを閉じると、パネルがステータス バーに追加されます。

ランタイムの場合

*Visual Basic の場合：*

----
Imports Infragistics.Win.UltraWinStatusBar
...
Private Sub WinStatusBarQuickTourTextPanel_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	' 新しいパネルを作成します。
	Dim myPanel As New UltraStatusPanel()
	' パネルのスタイルを設定します。
	myPanel.Style = PanelStyle.Text
	' デフォルト テキストを設定します。
	myPanel.Text = "This is My UltraStatusBar Text Panel"
	' パネルをエレメントに追加します。
	Me.UltraStatusBar1.Panels.Add(myPanel)
End Sub
----

*C# の場合：*

----
using Infragistics.Win.UltraWinStatusBar;
...
private void WinStatusBarQuickTourTextPanel_Load(object sender, System.EventArgs e)
{
	// 新しいパネルを作成します。
	UltraStatusPanel myPanel = new UltraStatusPanel();
	// パネルのスタイルを設定します。
	myPanel.Style = PanelStyle.Text;
	// デフォルト テキストを設定します。
	myPanel.Text = "This is My UltraStatusBar Text Panel";
	// パネルをエレメントに追加します。
	this.ultraStatusBar1.Panels.Add(myPanel);
}
----