////

|metadata|
{
    "name": "wintoolbarsmanager-add-tools-to-application-menu-2010",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "3556f393-e6e9-43db-a0f0-d50456ca9e75",  
    "buildFlags": [],
    "createdOn": "2010-09-23T21:32:15.6526815Z"
}
|metadata|
////

= ツールをアプリケーション メニュー 2010 に追加

UltraToolbarsManager™ コンポーネントの Office 2010 スタイル アプリケーション メニューは、ヘッダー、ナビゲーション メニュー、コンテンツ領域で構成されます。リボンの左上隅にあるメニュー ボタンをクリックすることによって、アプリケーション メニュー 2010 を開くことができます。Office 2010 スタイル アプリケーション メニューを起動するその他の方法は、 link:wintoolbarsmanager-office-2010-style-application-menu.html[「Office 2010 スタイル アプリケーション メニュー」]を参照してください。Office 2010 スタイル アプリケーション メニューが広がって、リボン タブの下のすべてのスペースを埋めます。これは標準的なアプリケーション メニューと異なります。

Office 2010 スタイル アプリケーション メニューのナビゲーション メニューは Button ツール、PopupMenu ツール、PopupControlContainer ツール、そしてメニューによってサポートされるほとんどすべてのツールを表示できます。

以下のコードは、ツールボックスからフォームに WinToolbarsManager™ コンポーネントを既にドラッグしてあり、 link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ribbon.html[ultraToolbarsManger.Ribbon] オブジェクトの link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ribbon~filemenustyle.html[FileMenuStyle] プロパティが ApplicationMenu2010 に設定されていることが前提となります。

コード例は、Button ツール、PopupMenu ツールおよび PopupControlContainer ツールを作成し、これらを ultraToolbarsManager コンポーネントのツール コレクションに追加して、次にアプリケーション メニュー 2010 のナビゲーション メニュー領域に追加する方法を示します。以下の例では、ultraMonthViewMulti コントロールは PopupControlContainerTool の Control プロパティに設定されるフォームに追加されます。

[NOTE]
====
*注：* Office 2010 スタイル ファイル メニュー ボタンが必要な場合、UltraToolbarsManager.Style プロパティを Office2010 に設定します。
====

*Visual Basic の場合：*

----
Imports Infragistics.Win.UltraWinToolbars
...
' ナビゲーション メニューに表示される Button ツールを作成します
Dim newBtnTool As New ButtonTool("NewBtnTool")
newBtnTool.SharedProps.Caption = "New"
' Button ツールを UltraToolbarsManager のツール コレクションに追加します
Me.UltraToolbarsManager1.Tools.Add(newBtnTool)
' PopupMenu ツールに追加できる List ツールを作成します
' このツールはコンテンツ領域に表示されます
Dim recentTool As New ListTool("Recent")
recentTool.ListToolItems.Add("doc1", "Document 1")
recentTool.ListToolItems.Add("doc2", "Document 2")
recentTool.ListToolItems.Add("doc3", "Document 3")
Me.UltraToolbarsManager1.Tools.Add(recentTool)
' ナビゲーション メニューに表示される PopupMenu ツールを作成します
Dim popupMenu1 As New PopupMenuTool("PopupRecent")
popupMenu1.Settings.PopupStyle = PopupStyle.Menu
popupMenu1.SharedProps.Caption = "Recent"
' PopupMenu ツールを UltraToolbarsManager のツール コレクションに追加します
Me.UltraToolbarsManager1.Tools.Add(popupMenu1)
popupMenu1.Tools.AddTool("Recent")
' ナビゲーション メニューに表示される PopupControlContainer ツールとコンテンツ領域に表示されるコントロールを作成します
Dim applicationmenu2010ContainerTool As New PopupControlContainerTool("PopupControlContainerTool")
applicationmenu2010ContainerTool.Control = Me.ultraMonthViewMulti1
applicationmenu2010ContainerTool.SharedProps.Caption = "Custom"
' PopupControlContainer ツールを UltraToolbarsManager のツール コレクションに追加します
Me.UltraToolbarsManager1.Tools.Add(applicationmenu2010ContainerTool)
Dim appmenu2010 As ApplicationMenu2010 = Me.UltraToolbarsManager1.Ribbon. ApplicationMenu2010
' Button ツールを Office 2010 スタイル アプリケーション メニューのナビゲーション メニューに追加します
appmenu2010.NavigationMenu.Tools.AddTool("NewBtnTool")
' Popup ツールを Office 2010 スタイル アプリケーション メニューのナビゲーション メニューに追加します
appmenu2010.NavigationMenu.Tools.AddTool("PopupRecent")
' PoupControlContainer ツールを Office 2010 スタイル アプリケーション メニューのナビゲーション メニューに追加します
appmenu2010.NavigationMenu.Tools.AddTool("PopupControlContainerTool")
----

*C# の場合：*

----
using Infragistics.Win.UltraWinToolbars;
...
// ナビゲーション メニューに表示される Button ツールを作成します
ButtonTool newBtnTool = new ButtonTool("NewBtnTool");
newBtnTool.SharedProps.Caption = "New";
// Button ツールを UltraToolbarsManager のツール コレクションに追加します
this.ultraToolbarsManager1.Tools.Add(newBtnTool);
// PopupMenu ツールに追加できる List ツールを作成します
// このツールはコンテンツ領域に表示されます
ListTool recentTool = new ListTool("Recent");
recentTool.ListToolItems.Add("doc1", "Document 1");
recentTool.ListToolItems.Add("doc2", "Document 2");
recentTool.ListToolItems.Add("doc3", "Document 3");
this.ultraToolbarsManager1.Tools.Add(recentTool);
// ナビゲーション メニューに表示される PopupMenu ツールを作成します
PopupMenuTool popupMenu1 = new PopupMenuTool("PopupRecent");
popupMenu1.Settings.PopupStyle = PopupStyle.Menu;
popupMenu1.SharedProps.Caption = "Recent";
// PopupMenu ツールを UltraToolbarsManager のツール コレクションに追加します
this.ultraToolbarsManager1.Tools.Add(popupMenu1);
popupMenu1.Tools.AddTool("Recent");
// ナビゲーション メニューに表示される PopupControlContainer ツールと
// コンテンツ領域に表示されるコントロールを作成します
PopupControlContainerTool applicationmenu2010ContainerTool = new PopupControlContainerTool("PopupControlContainerTool");
applicationmenu2010ContainerTool.Control = this.ultraMonthViewMulti1;
applicationmenu2010ContainerTool.SharedProps.Caption = "Custom";
// PopupControlContainer ツールを UltraToolbarsManager のツール コレクションに追加します
this.ultraToolbarsManager1.Tools.Add(applicationmenu2010ContainerTool);
ApplicationMenu2010 appmenu2010 = this.ultraToolbarsManager1.Ribbon. ApplicationMenu2010;
// Button ツールを Office 2010 スタイル アプリケーション メニューのナビゲーション メニューに追加します
appmenu2010.NavigationMenu.Tools.AddTool("NewBtnTool");
// Popup ツールを Office 2010 スタイル アプリケーション メニューのナビゲーション メニューに追加します
appmenu2010.NavigationMenu.Tools.AddTool("PopupRecent");
// PoupControlContainer ツールを Office 2010 スタイル アプリケーション メニューのナビゲーション メニューに追加します
appmenu2010.NavigationMenu.Tools.AddTool("PopupControlContainerTool");
----

関連トピック:

link:wintoolbarsmanager-customize-areas-of-application-menu-2010-and-file-menu-button.html[アプリケーション メニュー 2010 の領域およびファイル メニュー ボタンのカスタマイズ]