////

|metadata|
{
    "name": "wintabbedmdimanager",
    "controlName": ["WinTabbedMdiManager"],
    "tags": [],
    "guid": "{15A7F48C-3B13-46C3-9616-0D84BBA222FF}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTabbedMdiManager

WinTabbedMdiManager コンポーネントに関連した概要/タスクベースの情報のすべてが収められている領域を探しているのであれば、このページをご覧ください。このセクションは、コンポーネントについての概要からアプリケーションで使用する理由、コンポーネントを使用して一般的なタスクを完了するための方法の手順などの WinTabbedMdiManager についての有益な情報を含んでいます。

以下のリンクをクリックすると、WinTabbedMdiManager コントロールに関する重要な情報にアクセスします。

== link:wintabbedmdimanager-understanding-wintabbedmdimanager.html[WinTabbedMdiManager の理解]

このセクションでは、WinTabbedMdiManager コンポーネントの機能をより良く理解するために助けとなるあらゆる情報や、アプリケーション構築の一環としてこのコンポーネントの機能を使いたくなる理由が説明されています。

== link:win-wintabbedmanager-using-wintabbedmdimanager.html[WinTabbedMdiManager の使用]

このセクションは、WinTabbedMdiManager コントロールによって提供されるさまざまな特徴や機能を効率的に使用するための手助けとなるタスクベースの情報のゲートウェイです。

== link:wintabbedmdimanager-api-overview.html[API 概要]

このトピックでは、WinTabbedMdiManager コンポーネントを使用してプログラミングするときに取り扱う名前空間とクラスのリストを掲載しています。本トピックでリストされている名前空間とクラスは、{ProductName} ヘルプの「API リファレンスガイド」にリンクしています。