////

|metadata|
{
    "name": "wintimelineview-api-overview",
    "controlName": ["WinTimelineView"],
    "tags": ["API","Scheduling","Sorting"],
    "guid": "{17973F87-B59F-487F-8AE8-C9C5D688F75D}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API の概要

このセクションではコントロールに関連する各名前空間を示します。 このコントロールでプログラムする間に使用するいくつかのキー クラスも提供します。 このページの名前空間とクラスは当社の API マニュアルに直接リンクします。

=== WinTimelineView 名前空間：

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule_namespace.html[Infragistics.Win.UltraWinSchedule 名前空間]"]

=== キー クラス：

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.ultratimelineview.html[UltraTimelineView]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.owner.html[Owner]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.datetimeinterval.html[DateTimeInterval]"]