////

|metadata|
{
    "name": "wintoolbarsmanager-add-a-textbox-to-a-toolbar",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{F3CEF828-B9CD-4B8A-B5F4-69B7CA134FF4}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= TextBox をツールバーに追加

WinToolbarsManager コンポーネントには、pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar.html[ToolBar]"]  に追加できる 15 種類のツールが含まれています。ここでは、pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.textboxtool.html[TextBoxTool]"]  をデザインタイムおよびランタイムに追加する方法を示します。

== デザインタイムの場合

[start=1]
. UltraWinToolbar エレメントを設定するため、UltraToolbarManager エレメント上で右クリックし、[ユーザー設定] を選択して、[ユーザー設定] ダイアログを開きます。
[start=2]
. 新しいツールを作成するため、ユーザー設定の [ツール] タブをクリックしてから [新規] ボタンをクリックします。
[start=3]
. ツールの種類として TextBox ツールを選択し、[追加] ボタンをクリックします。
[start=4]
. ユーザー設定の [ツールバー] タブをクリックしてから [新規作成] ボタンをクリックします。
[start=5]
. [ツール] タブをクリックし、TextBox ツールをフォーム上の ToolBar にドラッグします。

== ランタイムの場合

*Visual Basic の場合：*

----
Imports Infragistics.Win.UltraWinToolbars
...
Private Sub AddaTextBoxtoaToolbar_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Dim TextTool As New TextBoxTool("ttool")
	Me.UltraToolbarsManager1.Tools.Add(TextTool)
	Me.UltraToolbarsManager1.Toolbars(0).Tools.Add(TextTool)
End Sub
----

*C# の場合：*

----
using Infragistics.Win.UltraWinToolbars;
...
private void AddaTextBoxtoaToolbar_Load(object sender, System.EventArgs e)
{
	TextBoxTool TextTool = new TextBoxTool("ttool");
	this.ultraToolbarsManager1.Tools.Add(TextTool);
	this.ultraToolbarsManager1.Toolbars[0].Tools.Add(TextTool);
}
----