////

|metadata|
{
    "name": "wintoolbarsmanager-about-wintoolbarsmanager",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{D4C7A0D8-01E8-4303-8C06-2805842C7FC1}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= WinToolbarsManager について

WinToolbarsManager の主な機能の一覧を次に示します。

* Microsoft Office と同様の*複数レベルのカスケードメニュー* 。
* Microsoft Office と同様の*ドッキング可能およびフローティング可能なツールバー* 。
* 1 つのプロパティ設定で *Office2000、OfficeXP、Office 2003、Visual Studio 2005、または Office 2007 のルック アンド フィール* を選択できます。
* フォーム上だけでなく*あらゆるコンテナ コントロール上で動作* します。メニューやツールバーを提供する複数の UltraToolbarsManager エレメントを、同じフォーム上にあるさまざまなコンテナ コントロールやフォーム自体に配置できます。
* *WYSIWYG のデザインタイム カスタマイザ* で簡単にメニュー、ツールバー、およびツールを作成できます。UltraToolbarsManager は、デザインタイム カスタマイズ ダイアログの使用と Visual Studio IDE 内のツールとツールバーのインプレース作成のサポートの両方をサポートします。
* Microsoft Office と同様の *TaskPane ツールバー* 。
* *ランタイム カスタマイザ* は、アプリケーションのツールバーとメニューをカスタマイズするためにアプリケーションのユーザーが起動できます。カスタマイザは、ドラッグ アンド ドロップ インタフェースを使用して、Microsoft Office のカスタマイザと同様の動作を実行します。
* *MDI メニューの自動マージ* の完全なサポート。UltraToolbarsManager コンポーネントを格納している MDI 子フォームおよびコンテナ フォームでは、子フォームのインスタンスがアクティブになったときにそれらのツールバーやメニューが自動的にマージされます。この動作はコードを記述しなくても実現されます。子のツールバー、メニュー、およびツールに関連するすべてのイベントが子フォーム内で発行されるため、子フォームにおけるツールバーの処理ロジックを完全にカプセル化できます。
* *分離型メニューのサポート* 。すべてのメニューの上部に「分離バー」を付けて表示できます。エンド ユーザーは分離バーを使用してメニューを切り離し、ツールバーとしてフローティングできます。この動作はメニューの持つ単一のプロパティ（AllowTearaway）を設定することで制御します。
* *ツールバー スタイルを使用した PopupMenu の表示* 。このオプションを設定すると、メニュー上のツールがボタンで表現され、フローティング ツールバーの場合と同様に横に並んで表示されます。このスタイルは、コンテキスト メニューとして表示される PopupMenu でも使用できるため、「コンテキスト ツールバー」を作成できます。
* *メニューのアニメーション* 。Microsoft Office で使用できるものと同じメニュー アニメーション タイプ（なし、ランダム、展開、スライド、およびフェード）から選択できます。
* *コンテキスト メニュー* 。UltraToolbars ポップアップメニューを任意のコントロールに追加して、デフォルトのコンテキスト メニューを簡単に置き換えることができます。UltraToolbarManager コントロールをフォームに配置すると、そのフォーム上のコントロールのうち ContextMenu プロパティを持つコントロールに、ContextMenuUltra プロパティが追加されます。このプロパティを使用して、UltraToolbars メニューをコントロールのコンテキスト メニューとして割り当てます。
* ツールは、ツールバーまたはメニューに*大きなアイコンまたは小さなアイコン* を表示できます。
* ツールの*柔軟なテキスト配置オプション* 。CaptionPlacement プロパティを使用すると、Button ツールでのテキストの表示位置を、ツールのイメージからの相対位置（上、下、イメージの左または右）で詳細に制御できます。
* バイナリ ストリームまたは SOAP 形式（XML）のストリームを使用して、プログラムから*ツールバー設定をロードおよび保存* できます。
* *広範なイベント* 。ツールバーやメニューで発生したあらゆるアクティビティをアプリケーションに通知します。
* メニューやツールバーで使用できる*豊富なツールタイプのセット* 。次のものがあります。

** *Button ツール*
** *ComboBox ツール*
** *ControlContainer ツール* - あらゆる .NET コントロールをホストできます。
** *FontListツール* - 使用可能なフォントのドロップダウン リストを、各エントリのフォントを使用して表示します。
** *Label ツール* - 静的なラベルをツールバーやメニューに表示します。
** *List ツール* - 個々のメニュー項目としてメニューに表示される、プログラム可能な文字列コレクションを格納します。MRU リストに最適です。
** *Masked Edit ツール* - 入力を制限するテキストのようなツールです。
** *MDIWindowList ツール* - PopupMenu ツールで、現在使用可能な MDI 子ウィンドウのリストを表示するために使用します。「重ねて表示」や「並べて表示」など、MDI ウィンドウの標準コマンドもあわせて表示します。
** *ProgressBar ツール* - 特定のタスクが完了した程度を示す進捗バーを表示します。
** *PopupColorPicker ツール* - Microsoft Office と同様の、色のドロップダウン リストを表示します。
** *PopupControlContainer ツール* - クリックされたときに、指定したすべてのコントロールを格納しているウィンドウをドロップダウン表示するツールを、メニューまたはツールバーに表示します。
** *PopupMenu ツール* - ドロップダウン メニューやコンテキスト メニューを表示します。
** *StateButton ツール* - ラジオ ボタンのように機能します。状態の切り替えはプログラムから行うことも、エンド ユーザーが手動で行うこともできます。
** *Textbox ツール*
** *TaskPane ツール* - タスク ペインの項目を表します。

* *1 ステップ メニュー インポート* 機能により、.NET アプリケーションの既存のメニューを UltraToolbarsManager メニューに変換できます。
* アプリケーションの既存の .Net ツールバーを UltraToolbarsManager ツールバーに変換できるツールバーの重要な機能です。
* *メニューおよびツールバーのパーソナライズ* 機能により、最近使用したツールバー項目やメニュー項目だけが表示されます。メニューでは、最近使用していない項目は、プログラムで設定した遅延時間が経過した後に表示されます。また、メニューの下にある下向きのシェブロンをクリックした場合はすぐに表示されます。ツールバーでは、最近使用していないツールは、ツールバーの QuickCustomize ボタンの向こうに「押し出されて」、ポップアップ メニューになります。
* ツールバーの *QuickCustomize ボタン* を使用すると、エンド ユーザーが [Add or Remove Buttons] サブメニューを通じてランタイムにツールバーをカスタマイズできます。
* *柔軟なツール イメージのサポート* 。 ツールごとに指定した 1 つのイメージから、ボタンの各状態に対応したイメージ（アップ、押下、無効）を自動的に生成します。
* *メニューのサイド ストリップ* - 垂直に表示されるテキストやイメージを格納できる垂直領域を、メニューの左端に表示できます。サイド ストリップの外観は Windows 2000 のスタート メニューと同じです。
* *フローティング ツールバーのフェード遅延* - 指定した時間が経過すると、フローティング ツールバーが 20% の不透明度にフェードします。マウス ポインタがツールバー上を通過すると、すぐに 100% の不透明度に戻ります。
* *イメージリストまたはイメージ ファイルからのツール イメージの取得* - ツールのイメージを指定するには、関連するツール イメージ プロパティを直接設定するか、または Imagelist 内のイメージを表すインデックスを設定します。