////

|metadata|
{
    "name": "wintoolbarsmanager-replace-a-controls-context-menu-with-a-popupmenu-tool",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{F46D4655-CB8A-4EC6-B268-64F82B5536A3}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= コントロールのコンテキスト メニューの PopupMenu ツールへの置換

WinToolbarsManager™ コンポーネントには、pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.popupmenutool.html[ポップアップメニューツール]"]  を、フォーム上の他のコントロールに対するコンテキストメニューとして表示する機能があります。これには、ContextMenuUltraプロパティを設定することで実行できます。

== デザイン時の場合：

PopupMenuTool を Tools コレクションに追加し、いくつかのその他のツールをポップアップ メニュー内に表示します。PopupMenuTool デザイナを使用すれば、PopupMenuTool 内にこれらのツールを配置できます。そして、テキストボックスなどの異なるコントロールをフォームに追加します。すると、テキストボックスのプロパティに、UltraToolBarsManager1のContextMenuUltraというプロパティが表示されます。このプロパティを選択すると、UltraToolBarsManagerコントロールにあるすべてのポップアップメニューツールがテキストボックス用のコンテキストメニューとして選択できるようになります。

== 実行時：

*Visual Basic の場合：*

----
Imports Infragistics.Win.UltraWinToolbars
...
Private Sub Replace_a_Controls_Context_Menu_with_a_PopupMenu_Tool_Load( _
  ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	' Creates a new popup menu and some buttons
	Dim FontWeight As New PopupMenuTool("FontWeight")
	Dim Bold As New ButtonTool("Bold")
	Dim Underline As New ButtonTool("Underline")
	' Adds the menu and the buttons to the tools collection
	Me.UltraToolbarsManager1.Tools.Add(FontWeight)
	Me.UltraToolbarsManager1.Tools.Add(Bold)
	Me.UltraToolbarsManager1.Tools.Add(Underline)
	' Adds the button tools to the menu
	FontWeight.Tools.Add(Bold)
	FontWeight.Tools.Add(Underline)
	'  Sets the caption to be displayed for the button tools
	Bold.SharedProps.Caption = "Bold"
	Underline.SharedProps.Caption = "Underline"
	' Sets the context menu for the TextBox control to the popup menu tool created
	Me.UltraToolbarsManager1.SetContextMenuUltra(Me.UltraTextEditor1, "FontWeight")
End Sub
----

*C# の場合：*

----
using Infragistics.Win.UltraWinToolbars;
...
private void Replace_a_Controls_Context_Menu_with_a_PopupMenu_Tool_Load(
  object sender, 
  EventArgs e)
{
	// Creates a new popup menu and some buttons
	PopupMenuTool FontWeight = new PopupMenuTool("FontWeight");
	ButtonTool Bold = new ButtonTool("Bold");
	ButtonTool Underline = new ButtonTool("Underline");
	// Adds the menu and the buttons to the tools collection
	this.ultraToolbarsManager1.Tools.Add(FontWeight);
	this.ultraToolbarsManager1.Tools.Add(Bold);
	this.ultraToolbarsManager1.Tools.Add(Underline);
	// Adds the button tools to the menu
	FontWeight.Tools.Add(Bold);
	FontWeight.Tools.Add(Underline);
	// Sets the caption to be displayed for the button tools
	Bold.SharedProps.Caption = "Bold";
	Underline.SharedProps.Caption = "Underline";
	// Sets the context menu for the TextBox control to the popup menu tool created
	this.ultraToolbarsManager1.SetContextMenuUltra(this.ultraTextEditor1, "FontWeight");
}
----