////

|metadata|
{
    "name": "wintree-wintree-columnsets-overview",
    "controlName": ["WinTree"],
    "tags": [],
    "guid": "{8BD264A3-6A3D-4828-982F-D1213D928898}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WinTree ColumnSets の概要

WinTree™ は、データの単一または複数列の表示をサポートします。この機能は pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratree.html[UltraTree]"]  オブジェクトの pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratree~columnsettings.html[ColumnSettings]"]  プロパティによって制御されます。ColumnSettings プロパティは WinTree コントロールによって表示される列に適用するすべてのプロパティを定義します。

Infragistics® WinGrid™ コントロールで経験がある場合、これらのプロパティのいくつかが pick:[win-forms="link:{ApiPlatform}win.ultrawingrid{ApiVersion}~infragistics.win.ultrawingrid.ultragridoverride.html[UltraGridOverride]"]  オブジェクトにあるプロパティに類似していることを知っておくと役立つ場合があります。

[NOTE]
====
*注：* ただし、UltraGridOverride オブジェクトのプロパティに似ているからといって、これらのプロパティが WinTree でも WinGrid と同様に動作するとは限りません。
====

pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreenodecolumn~columnset.html[ColumnSets]"]  プロパティは、pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.columnsetscollection.html[ColumnSetsCollection]"]  タイプで、これはそれぞれが pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreenodecolumn.html[UltraTreeNodeColumns]"]  のセットを定義する pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreecolumnset.html[UltraTreeColumnSet]"]  オブジェクトのコレクションです。UltraTreeColumnSet オブジェクトはツリーの列のセットにプロパティを定義します。これらのプロパティを使用すれば、複数のエンドユーザーによる列の操作を制限することが可能です。たとえば、pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreecolumnset~allowcolmoving.html[AllowColMoving]"]  は、列をドラッグ アンド ドロップして表示可能な場所を変更できるかどうかを決定します（詳細は、 link:wintree-move-columns-in-wintree.html[「WinTree 内で列を移動」]トピックを参照してください）。もうひとつの一般的に使用されるプロパティは、エンドユーザーが列ヘッダーをクリックして列の行をソートできるかどうかを決定する pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratreecolumnset~allowsorting.html[AllowSorting]"]  です（詳細は、 link:wintree-sort-columns-in-wintree.html[「WinTree 内で列をソート」]トピックを参照してください ）。これらのすべてのプロパティ設定は、UltraTreeColumnSettings オブジェクトを通して WinTree の ColumSets コレクション全体に適用可能です。また、個々の ColumnSet は、UltraTreeColumnSet および UltraTreeNodeColumn オブジェクトのプロパティを使用してオーバーライドできます。

[NOTE]
====
*注：* UltraTreeColumnSet および UltraTreeColumnSettings オブジェクトのすべてのプロパティは、WinTree コントロールの pick:[win-forms="link:{ApiPlatform}win.ultrawintree{ApiVersion}~infragistics.win.ultrawintree.ultratree~viewstyle.html[ViewStyle]"]  プロパティが 'Standard' 以外の値に設定されている場合に限って適用可能です。
====