////

|metadata|
{
    "name": "wintabbedmdimanager-about-wintabbedmdimanager",
    "controlName": ["WinTabbedMdiManager"],
    "tags": [],
    "guid": "{46F60497-7415-4D7E-88BE-8103A5E21687}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= WinTabbedMdiManager について

WinTabbedMdiManager の主な機能の一覧を次に示します。

* *タブ付きマルチ ドキュメント インタフェース（MDI）* - Microsoft Visual Studio.NET で見られるように、個々の MDI 子フォームがタブ項目によって表されます。
* *複数のタブ グループ* - タブ項目を複数の垂直または水平タブ グループに整理できます。
* *タブのスタイル* - VisualStudio、Excel、プロパティ ページなどを含む複数のタブ スタイルが使用できます。
* *タブのサイズ設定モード* - 固定幅、自動サイズ設定、サイズ調整などを含む、複数のタブ サイズ設定モードが使用できます。
* *タブとテキストの方向設定* - タブ項目とテキストの方向を詳細にカスタマイズできます。タブの位置は、MDI 子フォームの上、下、左、または右に設定できます。テキストの方向は、絶対的に設定するか、またはタブの方向に対して相対的に設定できます。
* *ドラッグ アンド ドロップ機能* - タブの位置をタブ グループ内部で変更したり、タブを他のタブグループにドラッグしたり、タブをドラッグして新しいタブ グループを作成したりできます。
* *MDI レイアウトの保存とロード* - MdiTab オブジェクトおよび MdiTabGroup の位置と設定をシリアル化できます。ロード処理中にカスタム イベントを呼び出して、関連付けられたフォームをロードすることが可能です。
* *階層的なコントロールの設定* - タブ項目の設定は、タブ レベル、タブ グループ レベル、またはエレメント レベルで設定できます。タブ グループの設定は、特定のタブ グループに対して、またはすべてのタブ グループに対して、設定できます。
* *サイズ変更可能なタブグループ* - タブ グループ間に分割バーが表示され、エンド ユーザーがタブ グループのサイズを変更できます。
* *カスタム コンテキスト メニュー* - デフォルトのコンテキスト メニューがタブ項目に対して表示されます。項目は追加または削除できます。
* *ViewStyle* - Visual Studio 2005、Office 2003、Office 2007、または標準スタイル表示のいずれかにタブ項目およびボタンのデフォルトの外観を変更するために使用できるコンポーネントのひとつのプロパティ（ViewStyle）です。
* *Presentation Layer Framework* - UltraTabbedMdiManager はプレゼンテーション レイヤー フレームワークの使用を可能にしているため、他の Infragistics ウィンドウ コントロールで使用できるものと同じ機能を備えています。たとえば、項目のオーナー描画（DrawFilter）、項目の位置の変更（CreationFilter）、カーソルの変更（CursorFilter）、イベントの動的な有効化および無効化（EventManager）が可能です。