////

|metadata|
{
    "name": "wintab-wintab-and-wintabstrip-terms-and-concepts",
    "controlName": ["WinTab"],
    "tags": ["Getting Started"],
    "guid": "{52949E29-ADBC-4561-8CD4-61772A547313}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= WinTab および WinTabStrip に関する用語と概念

* *タブ* - エレメントの基本的な要素。各タブは UltraTab オブジェクトによって表されます。UltraTab オブジェクトは、自身の固有のタブに関係する一連のプロパティとメソッドを公開しています。
* *Tabs コレクション* - エレメントは、UltraTab オブジェクトのコレクションを返す Tabs プロパティを公開しています。インデクサが提供されており、その Index または Key プロパティの設定を通じてタブにアクセスできます。
* *VisibleTabs コレクション* - コントロールは、同じ UltraTab オブジェクトのコレクションを返す VisibleTabs プロパティを公開しています。ただし、このコレクションはタブの表示順序を保持しています。インデクサが提供されており、その VisibleIndex プロパティの設定を通じてタブにアクセスできます。また、このコレクションはタブの表示順序を変更するための Sort メソッドも公開しています。
* *タブ ヘッダ領域* - タブとスクロール ボタンが表示されるエレメントの領域。
* *タブ ページ エレメント* - タブごとに UltraTabControl の Tab コレクションに作成される UltraTabPageControl。タブが選択されると、そのタブのタブ ページ コントロールがタブ ページ領域に表示され、他のすべてのタブ ページ コントロールは非表示になります。

*注* UltraTabStripControl ではすべてのタブで SharedControlsPage が使用されます。タブ単位のコントロールはサポートされていません。
* *タブ ページ領域* - 選択されたタブの TabPage コントロールがあるエレメントの領域。
* *クライアント領域* - タブ ヘッダ領域を除くエレメントの領域全体。
* *タブ ページ マージン* - タブ ページ領域を囲むクライアント領域内部のマージン領域。TabPageMargins プロパティは、左、上、右、下の各マージン範囲を指定するのに使用します。
* *共有コントロール* - 一部または全部のタブ間で共有されるコントロール。
* *共有コントロール ページ* - 共有コントロールは特殊な SharedControlsPage に配置されます。このページはタブ エレメントによって自動的に作成されます。タブが選択されると、これらのコントロールの親がそのタブのタブ ページに変更されます。

*注* 共有コントロール ページを表示するためのデザインタイム動詞があります。
* *共有コントロール コレクション* - SharedControls コレクションは、すべての共有コントロールを追跡管理します。このコレクションは、デザインタイムに共有コントロール ページに対してコントロールが追加または削除されるたびに、自動的に維持管理されます。
* *除外共有コントロール* - UltraTab オブジェクトでは ExcludedSharedControls プロパティが公開されています。このプロパティは、タブが選択されたときに親がそのタブに変更されない共有コントロールのコレクションを返します。注：このコレクションを容易に管理するためのダイアログを表示する、デザインタイム動詞があります。
* *アクティブなタブ、選択されたタブ* - ActiveTab は、フォーカスがあるタブです。SelectedTab は、タブ ページが表示されているタブです。常に 1 つのアクティブなタブと 1 つの選択されたタブが存在しますが、それらは必ずしも同じタブである必要はありません。たとえば、コントロールにフォーカスがあるときにユーザーがナビゲーション キー（[Tab] キーまたは矢印キー）を押すと、該当するタブがアクティブ化され、ActiveTabChanging イベントと ActiveTabChanged イベントが発生します。NavigationStyle プロパティの設定により、タブが同時に自動的に選択されて SelectedTabChanging イベントと SelectedTabChanged イベントが発生するかどうかが決まります。スペースキーまたは [Enter] キーを押すと、アクティブなタブがまだ選択されていなければ選択されます。

*注* ユーザーがタブをクリックしたときは、NavigationStyle の設定にかかわらず、タブは先にアクティブ化されてから選択されます。