////

|metadata|
{
    "name": "wintoolbarsmanager-create-a-popup-of-a-net-control-from-a-toolbar",
    "controlName": ["WinToolbarsManager"],
    "tags": [],
    "guid": "{94C44B02-492E-4EF7-88F6-F2F5C2D5C8C0}",  
    "buildFlags": [],
    "createdOn": "2005-07-07T00:00:00Z"
}
|metadata|
////

= ツールバーからの .NET コントロールのポップアップの作成

WinPopupControlContainer ツールを使用すると、ツールバーまたはメニューから .NET コントロールのポップアップを作成できます。このトピックは、WinCalendarCombo コントロールで作成する方法を説明します。

== デザインタイムで .NET コントロールのポップアップを作成

[start=1]
. UltraCalendarCombo エレメントを Toolbox に追加してから、UltraCalendarCombo をフォームに追加します。このエレメントの Visible プロパティを False に設定します。
[start=2]
. UltraWinToolbar エレメントを設定するため、UltraToolbarManager エレメント上で右クリックし、［ユーザー設定］を選択して、ユーザー設定ダイアログを開きます。
[start=3]
. 新しいツールを作成するため、ユーザー設定の [ツール] タブをクリックしてから [新規] ボタンをクリックします。
[start=4]
. PopupMenu ツールと PopupControlContainer ツール タイプを選択し、[追加] ボタンをクリックします。
[start=5]
. PopupControlContainer の Control プロパティを UltraCalendarCombo に設定します。
[start=6]
. ユーザー設定の [ツールバー] タブをクリックしてから [新規作成] ボタンをクリックします。
[start=7]
. [ツール] タブをクリックし、PopupMenu ツールをフォーム上の ToolBar にドラッグします。
[start=8]
. PopupControlContainer を PopupMenu にドラッグします。

== ランタイムで .NET コントロールのポップアップを作成

このコードは、2 つの pick:[win-forms="link:{ApiPlatform}win.ultrawintoolbars{ApiVersion}~infragistics.win.ultrawintoolbars.ultratoolbar.html[Toolbars]"]  を持つフォームによって異なり、UltraCalendarCombo2 という名前の UltraCalendarCombo も持ち、その Visible プロパティは False に設定されます。