////

|metadata|
{
    "name": "winvalidator-validate-a-group-of-controls",
    "controlName": ["WinValidator"],
    "tags": [],
    "guid": "{A21FC864-27E4-485E-9288-DA5DA39F1480}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= コントロールのグループを検証

WinValidator™ によってユーザーは、単一のコントロールを検証し、WinValidator に関連付けられたすべてのコントロールを検証し、コントロールのグループも検証できます。 link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.validationgroup.html[ValidationGroup] オブジェクトの新しいインスタンスをインスタンス化することでコントロールのグループを作成できます。作成したら、このオブジェクトを WinValidator の link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.ultravalidator~validationgroups.html[ValidationGroups] コレクションに追加する必要があります。

WinValidator は、検証作業を管理するために各コントロールに link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.validationsettings.html[ValidationSettings] オブジェクトを拡張します。このオブジェクトによって公開されるのは、 link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.validationsettings~validationgroup.html[ValidationGroup] プロパティです。このプロパティを有効な ValidationGroup に設定できます。ValidationGroups によってユーザーは、同様の条件と目的を持つコントロールを検証できます。ValidationGroups を使用すると、 link:{ApiPlatform}win.misc{ApiVersion}~infragistics.win.misc.validationsettings~validationtrigger.html[ValidationTrigger] がプログラマティックに設定されている場合に検証の順序を管理することもできます。

以下のコード例は、ValidationGroup の作成方法、それに 2 つのコントロールを追加する方法、そしてグループを検証する方法を示します。

*Visual Basic の場合：*

----
' 新しいグループを作成して WinValidator に追加します。
Me.UltraValidator1.ValidationGroups.Add( _
	New Infragistics.Win.Misc.ValidationGroup("TextGroup"))
' 2 つの TextBox コントロールの ValidationSettings オブジェクトを取得します。
Dim vs1 As Infragistics.Win.Misc.ValidationSettings = _
	Me.UltraValidator1.GetValidationSettings(Me.textBox1)
Dim vs2 As Infragistics.Win.Misc.ValidationSettings = _
	Me.UltraValidator1.GetValidationSettings(Me.textBox2)
' TextBox のテキストが "ultra" で開始する場合に
' 検証が失敗する新しい条件を作成します。
Dim condition As Infragistics.Win.OperatorCondition = _
	New Infragistics.Win.OperatorCondition( _
		Infragistics.Win.ConditionOperator.DoesNotStartWith, _
		"ultra")
' 2 つの ValidationSettings オブジェクトで条件を設定します。
vs1.Condition = condition
vs2.Condition = condition
' 適切なメソッドまたはイベントで、グループのキーを
' 渡すことでグループを検証します。
Me.UltraValidator1.Validate("TextGroup")
----

*C# の場合：*

----
// 新しいグループを作成して WinValidator に追加します。
this.ultraValidator1.ValidationGroups.Add(
	new Infragistics.Win.Misc.ValidationGroup("TextGroup"));
// 2 つの TextBox コントロールの ValidationSettings オブジェクトを取得します。
Infragistics.Win.Misc.ValidationSettings vs1 = 
	this.ultraValidator1.GetValidationSettings(this.textBox1);
Infragistics.Win.Misc.ValidationSettings vs2 =
	this.ultraValidator1.GetValidationSettings(this.textBox2);
// TextBox のテキストが "ultra" で開始する場合に
// 検証が失敗する新しい条件を作成します。
Infragistics.Win.OperatorCondition condition =
	new Infragistics.Win.OperatorCondition(
		Infragistics.Win.ConditionOperator.DoesNotStartWith,
		"ultra");
// 2 つの ValidationSettings オブジェクトで条件を設定します。
vs1.Condition = condition;
vs2.Condition = condition;
// 適切なメソッドまたはイベントで、グループのキーを
// 渡すことでグループを検証します。
this.ultraValidator1.Validate("TextGroup");
----