////

|metadata|
{
    "name": "winweekview-api-overview",
    "controlName": ["WinWeekView"],
    "tags": ["API"],
    "guid": "{2FA1AEB5-7A8B-4E82-B9E2-F948F0D092AB}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API 概要

このセクションはコントロールに関連する各名前空間をリストします。また、このコントロールでプログラミングをする時に使用するいくつかのキー クラスも示します。このページの名前空間とクラスは、Infragistics の API ドキュメントに直接リンクされています。

=== WinWeekView 名前空間:

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview_namespace.html[Infragistics.Win.UltraWinSchedule.WeekView]"]

=== キー クラス:


link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview.currentdaynumberselectionareauielement.html[CurrentDayNumberSelectionAreaUIElement]


pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview.daynumberuielement.html[DayNumberUIElement]"]

pick:[win-forms="link:{ApiPlatform}win.ultrawinschedule{ApiVersion}~infragistics.win.ultrawinschedule.weekview.weekareauielement.html[WeekAreaUIElement]"]