////
|metadata|
{
    "name": "datachart-category-range-bar-series",
    "controlName": ["{DataChartName}"],
    "tags": ["Application Scenarios","Charting","How Do I"],
    "guid": "f0cd173a-e80d-47d8-a96b-577b30d9ecdc",
    "buildFlags": [],
    "createdOn": "2026-05-21T00:00:00Z"
}
|metadata|
////

= Range Bar Series

This topic explains, with code examples, how to use the link:{DataChartLink}.RangeBarSeries.html[RangeBarSeries] in the link:{DataChartLink}.{DataChartName}.html[{DataChartName}]™ control.

== Overview

The topic is organized as follows:

* <<Introduction,Introduction>>
* <<DataRequirements,Data Requirements>>
* <<DataRenderingRules,Data Rendering Rules>>
* <<DataBindingExample,Data Binding Example>>
* <<SeriesProperties,Series Properties>>
* <<RelatedContent,Related Content>>

[[Introduction]]
== Introduction

Range Bar Series belongs to a group of link:datachart-category-series-overview.html[Category Series] and it is rendered using a collection of horizontal bars that show the difference between two values of a data point. This type of series emphasizes the amount of change between low values and high values in the same data point or compares multiple items. Range values are represented on the x-axis (NumericXAxis) and categories are displayed on the y-axis (CategoryYAxis). The link:{DataChartLink}.RangeBarSeries.html[RangeBarSeries] is the vertical counterpart to the link:{DataChartLink}.RangeColumnSeries.html[RangeColumnSeries] in the same way that the link:{DataChartLink}.BarSeries.html[BarSeries] is the vertical counterpart to the link:{DataChartLink}.ColumnSeries.html[ColumnSeries]. For more conceptual information and supported types of axes, refer to the link:datachart-category-series-overview.html[Category Series] and link:datachart-axes.html[Chart Axes] topics.

[[DataRequirements]]
== Data Requirements

While the {DataChartName} control allows you to easily bind it to your own data model, make sure to supply the appropriate amount and type of data that the series requires. If the data does not meet the minimum requirements based on the type of series that you are using, an error is generated by the control. Refer to the link:datachart-series-requirements.html[Series Requirements] and link:datachart-category-series-overview.html[Category Series] topics for more information on data series requirements.

The following is a list of data requirements for the `RangeBarSeries` type:

* The data model must contain at least two numeric data columns for rendering the range between the values.
* The data model may contain an optional string or date time field for labels.
* The data source should contain at least one data item.

[[DataRenderingRules]]
== Data Rendering Rules

The `RangeBarSeries` renders data using the following rules:

* Each row with two data values specified as the link:{DataChartLink}.RangeCategorySeries{ApiProp}LowMemberPath.html[LowMemberPath] and link:{DataChartLink}.RangeCategorySeries{ApiProp}HighMemberPath.html[HighMemberPath] properties of the data mapping is drawn as a separate horizontal bar representing the difference between these data values.
* The string or date time column that is mapped to the `Label` property of data mapping on the y-axis is used as the category labels. If the data mapping for `Label` is not specified, default labels are used.
* Category labels are drawn on the y-axis. Data values are drawn on the x-axis.
* When rendering, multiple series of the `RangeBarSeries` type will get rendered in clusters where each cluster represents a data point. The first series in the `Series` collection of the {DataChartName} control renders at the bottom of the cluster. Each successive series is rendered above the previous series. For more information, refer to the link:datachart-multiple-series.html[Multiple Series] topic.

[[DataBindingExample]]
== Data Binding Example

The following code snippet shows how to bind the link:{DataChartLink}.RangeBarSeries.html[RangeBarSeries] object to a sample of category data (which is available for download from the link:resources-sample-energy-data.html[Sample Energy Data] resource). Refer to the data requirements section of this topic for information about data requirements for the `RangeBarSeries`.

ifdef::win-forms[]
*In C#:*
[source,csharp]
----
var data = new EnergyDataSource();
var xAxis = new NumericXAxis();
var yAxis = new CategoryYAxis();
yAxis.DataSource = data;
yAxis.Label = "{Country}";

var series1 = new RangeBarSeries();
series1.DataSource = data;
series1.HighMemberPath = "Coal";
series1.LowMemberPath = "Oil";
series1.Title = "Coal vs Oil";
series1.XAxis = xAxis;
series1.YAxis = yAxis;

var series2 = new RangeBarSeries();
series2.DataSource = data;
series2.HighMemberPath = "Hydro";
series2.LowMemberPath = "Nuclear";
series2.Title = "Hydro vs Nuclear";
series2.XAxis = xAxis;
series2.YAxis = yAxis;

var chart = new {DataChartName}();
chart.Axes.Add(xAxis);
chart.Axes.Add(yAxis);
chart.Series.Add(series1);
chart.Series.Add(series2);
----

*In Visual Basic:*
[source,vb]
----
Dim data As New EnergyDataSource()
Dim xAxis As New NumericXAxis()
Dim yAxis As New CategoryYAxis()
yAxis.DataSource = data
yAxis.Label = "{Country}"

Dim series1 As New RangeBarSeries()
series1.DataSource = data
series1.HighMemberPath = "Coal"
series1.LowMemberPath = "Oil"
series1.Title = "Coal vs Oil"
series1.XAxis = xAxis
series1.YAxis = yAxis

Dim series2 As New RangeBarSeries()
series2.DataSource = data
series2.HighMemberPath = "Hydro"
series2.LowMemberPath = "Nuclear"
series2.Title = "Hydro vs Nuclear"
series2.XAxis = xAxis
series2.YAxis = yAxis

Dim chart As New {DataChartName}()
chart.Axes.Add(xAxis)
chart.Axes.Add(yAxis)
chart.Series.Add(series1)
chart.Series.Add(series2)
----
endif::win-forms[]

[[SeriesProperties]]
== Series Properties

The `RangeBarSeries` supports the same low/high value mapping behavior as other range series and also provides the following commonly used properties:

[options="header", cols="a,a"]
|====
|Property |Description

|`HighMemberPath`
|Specifies the data column that contains the high value for each horizontal range bar.

|`LowMemberPath`
|Specifies the data column that contains the low value for each horizontal range bar.

|`RadiusX` and `RadiusY`
|Specify the corner radius applied to the rendered bars.

|`LowMemberAsLegendLabel` and `HighMemberAsLegendLabel`
|Specify custom labels for the low and high values displayed by the Data Legend.

|`LowMemberAsLegendUnit` and `HighMemberAsLegendUnit`
|Specify custom units for the low and high values displayed by the Data Legend.
|====

[[RelatedContent]]
== Related Content

* link:datachart-axes.html[Axes]
* link:datachart-category-bar-series.html[Bar Series]
* link:datachart-category-range-column-series.html[Range Column Series]
* link:datachart-category-range-area-series.html[Range Area Series]
* link:datachart-series-requirements.html[Series Requirements]
