////
|metadata|
{
    "name": "piechart-others-category",
    "controlName": ["{PieChartName}"],
    "tags": ["How Do I"],
    "guid": "5b5ba0e9-953a-4a6c-84d3-0a4d1641c57b",
    "buildFlags": ["SL","WPF","win-phone","XAMARIN","ANDROID","WINFORMS"],
    "createdOn": "2014-06-05T19:53:12.0768992Z"
}
|metadata|
////

= Others Category

This topic demonstrates how to configure the Others category for the link:{DataPieChartLink}.{DataPieChartName}.html[{DataPieChartName}] control. At the end of the topic, the complete code sample is provided.

The topic is organized as follows:

* <<Introduction,Introduction>>
* <<Requirements,Requirements>>
* <<Configuring,Configuring the Others Category>>
* <<CodeExample, Code Example>>
* <<RelatedTopics,Related Content>>

[[Introduction]]
== Introduction

Sometimes, the underlying data for the Data Pie Chart control will contain many items with small values. In this case, the Others category will permit automatic aggregation of several data values into a single slice.

[[Requirements]]
== Requirements

This topic assumes you have already read the link:data-pie-chart-data-binding.html[Data Binding] topic, and uses the code therein as a starting point.


[[Configuring]]
== Configuring the Others Category

The Others category in the {DataPieChartName} has three main, configurable properties - `OthersCategoryType`, `OthersCategoryThreshold`, and `OthersCategoryText` that allow you to configure how the Others slice in the chart is shown. These are each described below:

The `OthersCategoryType` property works in tandem with the `OthersCategoryThreshold` property of the {DataPieChartName}. For the `OthersCategoryType`, you can define whether you want the `OthersCategoryThreshold` to be evaluated as a number or a percentage. For example, if you decide on number and set the `OthersCategoryThreshold` to 5, any slices that have a value less than 5 will become part of the Others category. Using the same value of 5 with a percent type, any values that are less than 5 percent of the total values of the {DataPieChartName} will become part of the Others category.

By default, the Others slice will be represented by a label of "Others." You can change this by modifying the `OthersCategoryText` property of the chart.

If you want to ensure that the Others category does not show up in the {DataPieChartName}, you can set the `OthersCategoryThreshold` to 0.

[[CodeExample]]
== Code Example

The following code example demonstrates the usage of the Others category in the {DataPieChartName}.

ifdef::wpf[]

*In XAML:*

[source,xaml]
----
TODO
----

*In C#:*

[source,csharp]
----
TODO
----

endif::wpf[]

ifdef::win-forms[]

*In C#:*

[source,csharp]
----
{DataPieChartName} dataPieChart = new {DataPieChartName}()
{                
    DataSource = data,
    Dock = DockStyle.Fill,                
    OthersCategoryThreshold = 3,
    OthersCategoryType = OthersCategoryType.Number,
    OthersCategoryText = "Others Custom"
};

this.Controls.Add(dataPieChart);
----

endif::win-forms[]



[[RelatedTopics]]
== Related Content

* link:data-pie-chart-data-binding.html[Data Binding]
* link:data-pie-chart-selection.html[Selection]